### ISSUE TITLE
Issue with text blocks formatting on java 21. Defaulting to extreme left indentation 

### ISSUE THREAD

**Issue by rohan-changejar** [diffplug/spotless#2138] opened 2024-05-24 11:19 UTC
- [ ]  Issue description - While trying to migrate our existing string implementations of string append to the latest text block format 
in our java 21 project, we are seeing that text blocks are not being handled properly and therefore causing unexpected left indentation, which is deviant from the standard formatting pattern
    
- [ ] Gradle or Maven version -     id "com.diffplug.spotless" version "6.17.0"
- [ ] operating system and version - MacOs sonoma 14.5
- [ ] `spotless {
    java {
//        googleJavaFormat()
        // optional: you can specify a specific version (>= 1.8) and/or switch to AOSP style
        //   and/or reflow long strings
        //   and/or use custom group artifact (you probably don't need this)
        googleJavaFormat('1.22.0').aosp().reflowLongStrings().groupArtifact('com.google.googlejavaformat:google-java-format')    }
}`

<img width="940" alt="image" src="https://github.com/diffplug/spotless/assets/83759161/148c2dbe-5973-4f17-b3f1-c2823e85f4df">

**Comment by bmarwell** [comment] 2024-05-27 13:55
DUplicate of https://github.com/diffplug/spotless/issues/1628

**Comment by nedtwigg** [comment] 2024-06-04 18:38
I think this is probably a bug in `googleJavaFormat`, not specific to Spotless. I don't think this is related to #1628, the configuration above does not use our indentStep

**Closed by nedtwigg** 2024-06-04 18:38 UTC
