### ISSUE TITLE
Regression in 2.41.0, no longer ignoring target/generated-sources

### ISSUE THREAD

**Issue by hylkevds** [diffplug/spotless#1914] opened 2023-11-27 15:39 UTC
Version 2.40.0 works without problems, switching to 2.41.0 fails the build due to formatting violations in code in `target/generated-sources`. Naturally, source code in `target` should not be checked for formatting violations.
The Changelog mentions #1846 that is probably related, but I'm not sure what config option to use to fix the issue.

- Apache Maven 3.8.6
- Linux Mint
- Repository: https://github.com/FraunhoferIOSB/FROST-Server
  Spotless version is line 139 of the pom.xml
- Failed build: https://github.com/FraunhoferIOSB/FROST-Server/actions/runs/7001504245/job/19043692393?pr=1826

If you are submitting a **bug**, please include the following:

- [x] summary of problem
- [x] Gradle or Maven version
- [x] spotless version
- [x] operating system and version
- [x] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
- [x] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`

**Comment by hylkevds** [comment] 2023-11-27 16:22
Found the fix:
```
                            <excludes>
                                <exclude>target/**</exclude>
                            </excludes>
```
in the `<java>` configuration block.
If excluding `target` by default is not feasible, then it may a good idea to add that to the examples.

**Comment by julius-d** [comment] 2023-11-27 16:23
I tried to update my project to spotless-maven-plugin version 2.41.0 but it fails with:
```
Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.41.0:check (default) on project my-service: The following files had format violations:
     target/generated-sources/openapi/src/main/java [...]
```
I think that the `generated-sources` should not be checked by default!

**Comment by basil** [comment] 2023-11-27 18:39
Same issue in the Jenkins project — all our builds are now failing due to this regression.

> I think that the `generated-sources` should not be checked by default!

Agreed.

**Comment by nedtwigg** [comment] 2023-11-28 00:05
For anybody who has this problem, can you please

- 👍 if adding `<exclude>target/**</exclude>` would have made this seamless for you
- 👎 if you still would have a problem, and so you wish that reverted #1847 altogether

**Comment by jlorenzen** [comment] 2023-11-28 15:48
Ran into this issue on all my team's projects. I think I would prefer maintaining backwards compatible behavior.
If one wants to run spotless on generated code, they should change the output directory to `src/main/java` so they can check the code in. Not sure why you'd want to run spotless on generated code that is not checked in.

**Closed** 2023-12-03 16:36 UTC

**Comment by nedtwigg** [comment] 2023-12-04 07:33
We went with a full revert to the previous behavior in `plugin-maven 2.41.1`. If it comes back, it'll be flag-gated and possibly also enhanced with `.gitignore`, tbd.
