### ISSUE TITLE
Javadoc on javadoc.io is broken

### ISSUE THREAD

**Issue by nsutcliffe** [diffplug/spotless#909] opened 2021-08-09 09:17 UTC
There appears to be an issue with publishing javadoc since 5.6.1. For example if you browse to:

https://javadoc.io/doc/com.diffplug.spotless/spotless-plugin-gradle/5.7.0/index.html

It gives the error:

_No JavaDoc is released for artifact com.diffplug.spotless:spotless-plugin-gradle:5.7.0. Please try other versions._

Here's a working link for 5.6.1 (if you change the version in the drop down, then it'll give an error like the above, unless you pick the latest version 5.14.2 from the dropdown, and it forwards you to the docs for 5.6.0)

https://javadoc.io/doc/com.diffplug.spotless/spotless-plugin-gradle/5.6.1/index.html

**Comment by nedtwigg** [comment] 2021-08-09 19:16
Thanks, known broken, I should really get around to fixing this, but I'm swamped. Dupe of #775

**Closed by nedtwigg** 2021-08-09 19:16 UTC
