### ISSUE TITLE
Auto clear configuration cache

### ISSUE THREAD

**Issue by WildOrangutan** [diffplug/spotless#1895] opened 2023-11-20 16:58 UTC
Until #987 is properly fixed, would it be possible to auto-clear configuration cache somehow? I get this error multiple times a day and it's getting annoying to manually deal with it all the time.

```
* What went wrong:                                                                                  
Execution failed for task ':spotlessKotlinGradle'.                                                  
> Error while evaluating property 'lineEndingsPolicy' of task ':spotlessKotlinGradle'.              
   > Spotless JVM-local cache is stale. Regenerate the cache with                                   
       rm -rf .gradle/configuration-cache                                                           
     To make this workaround obsolete, please upvote https://github.com/diffplug/spotless/issues/987
```

**Comment by nedtwigg** [comment] 2023-11-20 17:50
- Dupe of #1209

**Closed by nedtwigg** 2023-11-20 17:50 UTC
