### ISSUE TITLE
Eclipse formatter 4.20 and 4.21 are broken for records

### ISSUE THREAD

**Issue by marko-radosavljevic** [diffplug/spotless#951] opened 2021-09-28 14:15 UTC
Summary of the problem:

Updating from spotless 5.15.0 to 5.15.1/5.15.2 breaks formatting.

After closer inspection, using `eclipse()` breaks formatting (mostly inside a _record_), since eclipse version is updated to 4.20, and then 4.21.

Temporary fix is to hardcode eclipse version to '4.19.0'.
  
Gradle or maven version:

Introduced in gradle 5.15.1;
Reproducible in gradle 5.15.2;

operating system and version:

Ubuntu 20.04

Spotless configuration:

```groovy
    spotless {
        java {
            // Excludes build folder since it contains generated java classes.
            targetExclude("build/**")
            eclipse().configFile("${rootProject.rootDir}/meta/formatting/google-style-eclipse.xml")
        }
    }
```

Issue noticed in: https://github.com/Together-Java/TJ-Bot/pull/140, here you can find failing spotless check and diff of affected file.
'Fixed' in: https://github.com/Together-Java/TJ-Bot/pull/151
Root gradle: https://github.com/Together-Java/TJ-Bot/blob/develop/build.gradle
Slightly modified google style xml: https://github.com/Together-Java/TJ-Bot/blob/develop/meta/formatting/google-style-eclipse.xml

**Comment by nedtwigg** [comment] 2021-09-29 17:14
Each time a new version of an existing formatter comes out and we bump our default version, there is a chance that formatting will change. One way to avoid this is to pin the formatter version (as you have done with `eclipse('4.19.0')`, and another way is to use [ratcheting](https://github.com/diffplug/spotless/tree/main/plugin-gradle#ratchet) to make sure that the formatter changes only affect files that are changing anyway.

Our general philosophy for handling the changing of these defaults [is laid out here](https://github.com/diffplug/spotless/pull/940#issuecomment-923179382).

However, the case you are describing is quite extreme, and it sure looks like the eclipse formatter is just plain broken for java record classes starting with 4.20

![image](https://user-images.githubusercontent.com/2924992/135316941-16d19cac-e451-48bc-b229-728d82e6fc02.png)

It could be that we need to make some changes to this line

https://github.com/diffplug/spotless/blob/a9e83576e3f1dd6dfdf8c409c798b31849320049/_ext/eclipse-jdt/src/main/java/com/diffplug/spotless/extra/eclipse/java/EclipseJdtFormatterStepImpl.java#L57

@fvgh is the expert here, but it may be the case that this will just be broken until Eclipse 4.22 or later.

**Comment by fvgh** [comment] 2021-09-29 20:03
I am afraid it seems a Spotless error. Only quickly checked the formatting with Eclipse 2021-06 (4.20.0). I will see what I can achieve on the weekend. Help is always welcome :smile:  

@nedtwigg Thanks for the hint. There seems also a bug in the `format` statements, but that should only affect module-info. We need to extend the interface for the `spotless-eclipse-jdt`. It should detect a module-info by filename.

**Comment by fvgh** [comment] 2021-10-03 12:45
#957 proves the correct integration of the JDT formatter into Eclipse.
The erroneous formatting reported within this issue is caused by the configuration used by TJ-Bot.
Formatting with default Eclipse configuration (build.gradle):
```groovy
    spotless {
        java {
            // Excludes build folder since it contains generated java classes.
            targetExclude("build/**")
            eclipse('4.21.0')
        }
    }
```

Results in `formatter/src/main/java/org/togetherjava/formatter/tokenizer/Token.java`:
```java
import java.util.Set;

/**
 * Class representing a Token with a given content and a type
 *
 * @author illuminator3
 */
public record Token(String content, TokenType type) {
        private static final Set<TokenType> displayTypes = Set.of(TokenType.IDENTIFIER, TokenType.UNKNOWN, TokenType.STRING,
                        TokenType.COMMENT);

        @Override
        public String toString() {
                return type().name() + formatForDisplay();
        }

        /**
         * Returns a non-empty string if this token has something to display
         *
         * @return the displayed value
         * @author illuminator3
         */
        private String formatForDisplay() {
                if (displayTypes.contains(type())) {
                        return "(" + content() + ")";
                }

                return "";
        }
}
```

@marko-radosavljevic Please check your Eclipse configuration. Seems it causes conflicts using latter formatter versions.

**Comment by fvgh** [comment] 2021-10-10 07:09
@marko-radosavljevic Closing this issue since I found no problems on Spotless side. Feel free to reopen if you have  more input I should look into.

**Closed by fvgh** 2021-10-10 07:09 UTC
Labels: bug-unconfirmed

**Comment by marko-radosavljevic** [comment] 2021-10-12 16:12
Thanks a lot for the help, I really appreciate it. ^^

I will further investigate our eclipse configuration and make it compatible with newer formatter versions.

**Comment by moritz-tiedje** [comment] 2024-09-18 16:05
We ran into the same problem in a java 17 project. We used [eclipse-java-google-style](https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml) out of the box:
```
<plugin>
  <groupId>com.diffplug.spotless</groupId>
  <artifactId>spotless-maven-plugin</artifactId>
  <version>2.43.0</version>
  <configuration>
    <java>
      <eclipse>
        <version>4.26</version>
        <file>${project.basedir}/eclipse-java-google-style.xml</file>
      </eclipse>
    </java>
  </configuration>
</plugin>
```

The problem was not on the Spotless side. We fixed it by removing the following line from `eclipse-java-google-style.xml`:

`<setting id="org.eclipse.jdt.core.compiler.source" value="1.7"/>`
