### ISSUE TITLE
spotless groovy apply task fails with 403 error for goovy.eclipse.codebrowsing_5.1.0.v202309291934-e2309.jar

### ISSUE THREAD

**Issue by subhashiniv** [diffplug/spotless#2213] opened 2024-07-31 20:20 UTC
When i run my build gradle , it was able to download all jars except the below one.

 Could not create task ':spotlessGroovy'.
java.io.IOException: Failed to load eclipse groovy formatter: java.lang.IllegalArgumentException: 403 at https://groovy.jfrog.io/artifactory/plugins-release/org/codehaus/groovy/groovy-eclipse-integration/5.1.0/e4.29/plugins/org.codehaus.groovy.eclipse.codebrowsing_5.1.0.v202309291934-e2309.jar

Here is my groovy and groovy gradle section. spotless java apply works well though. I am using Intellij IDE. I am also able to download the jar from the browser when i am outside my VPN. In Intellij i have set the proxy settings, also included proxy settings in gradle.properties file. could you please help  me here in fixing the issue.

 groovy {
    // Use the default importOrder configuration
    importOrder()

    excludeJava() // excludes all Java sources within the Groovy source dirs from formatting
    greclipse() // has its own section below
    licenseHeaderFile rootProject.file("license")
    indentWithSpaces(2)
  }
  groovyGradle {
    target '*.gradle' // default target of groovyGradle
    greclipse()
    indentWithSpaces(2)
  }

**Comment by nedtwigg** [comment] 2024-08-12 00:47
- dupe of #1658

**Closed by nedtwigg** 2024-08-12 00:47 UTC
