### ISSUE TITLE
Build fails due to missing spotless-lib 2.21.2

### ISSUE THREAD

**Issue by dradtke** [diffplug/spotless#1090] opened 2022-01-12 21:23 UTC
I'm attempting to build my project with Gradle and Spotless 6.1.2, but it's failing with this error:

```
A problem occurred configuring root project 'api'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.diffplug.spotless:spotless-lib:2.21.2.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/com/diffplug/spotless/spotless-lib/2.21.2/spotless-lib-2.21.2.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.                                                                                                                
     Required by:
         project : > com.diffplug.spotless:com.diffplug.spotless.gradle.plugin:6.1.2 > com.diffplug.spotless:spotless-plugin-gradle:6.1.2
   > Could not find com.diffplug.spotless:spotless-lib-extra:2.21.2.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/com/diffplug/spotless/spotless-lib-extra/2.21.2/spotless-lib-extra-2.21.2.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.                                                                                                                
     Required by:
         project : > com.diffplug.spotless:com.diffplug.spotless.gradle.plugin:6.1.2 > com.diffplug.spotless:spotless-plugin-gradle:6.1.2
```

[This page](https://repo.gradle.org/ui/native/jcenter/com/diffplug/spotless/spotless-lib) seems to indicate that 2.15.0 is the latest version of `spotless-lib`.

Downgrading my Spotless plugin to 5.14.0 appears to fix the issue.

Any idea why this dependency might be missing?

**Comment by nedtwigg** [comment] 2022-01-12 21:42
Dupe of #1088.

**Closed by nedtwigg** 2022-01-12 21:42 UTC
