### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by nedtwigg** [diffplug/spotless#63] opened 2017-01-06 02:00 UTC
I just published 3.0.0.BETA2.  It's still waiting for approval on the gradle plugin portal because of the groupId/artifactId change, but it's up on jcenter and mavencentral here: `com.diffplug.spotless:spotless-plugin-gradle:3.0.0.BETA2`

Let's bang on it a little and make sure it's ready to go.  I know it's got some issues, let's hunt them down and ship this sucker!

**Comment by jbduncan** [comment] 2017-01-06 02:20
Awrigh' cap'n! 😀

I'll test this on my university dissertation when I have the time, and if I come across anything breaking, I'll report back here and/or raise an issue.

**Comment by jbduncan** [comment] 2017-01-06 22:38
I've tested 3.0.0.BETA2 against my dissertation, and unfortunately it reports an error message similar to the following when `./gradlew build` is run for a second or third time:

```text
:generateGrammarSource UP-TO-DATE
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:startScripts UP-TO-DATE
:distTar UP-TO-DATE
:distZip UP-TO-DATE
:assemble UP-TO-DATE
:spotlessAntlr FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spotlessAntlr'.
> java.nio.file.AccessDeniedException: C:\path\to\project\build\classes\test

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.941 secs

```

My Spotless config is as follows:
```groovy
spotless {
  java {
    target fileTree(rootDir) {
      include '**/*.java'
      exclude '**/generated/**', '**/generated-src/**'
    }
    googleJavaFormat('1.1')
  }

  format('antlr') {
    target '**/*.g4'

    trimTrailingWhitespace()
    indentWithSpaces(4)
    endWithNewline()
  }

  format('misc') {
    target '**/*.gradle', '**/.gitignore', '**/.gitattributes', '**/.editorconfig', '**/*.properties'

    trimTrailingWhitespace()
    indentWithSpaces(2)
    endWithNewline()
  }

  encoding 'UTF-8'
  lineEndings 'GIT_ATTRIBUTES'
}
```

**Comment by jbduncan** [comment] 2017-01-06 22:40
(I'm using Gradle 3.3.)

**Comment by nedtwigg** [comment] 2017-01-07 01:05
Looks like it's trying to format a folder rather than a file.  Wonder why a folder is getting into the FileCollection...

**Comment by nedtwigg** [comment] 2017-01-07 01:37
@oehme For [this code](https://github.com/diffplug/spotless/blob/b335462e990f57660b6ecbdaf36a5c8f91b838a9/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java#L147-L158), if we pass `'**/*.g4;'`, it should never match a directory, correct?

**Comment by nedtwigg** [comment] 2017-01-07 01:39
I uploaded a folder-exclusion in 5f3d1e45ed7ce8063cec9cf2ebfb04c4e44db11d, should be in 3.0.0-SNAPSHOT soon.  Does that fix your issue @jbduncan?

**Comment by oehme** [comment] 2017-01-07 11:37
It shouldn't match one, but maybe it got in through some other code path. In any case ignoring folders in the task itself is probably a good idea. Failing would be another alternative.

**Comment by jbduncan** [comment] 2017-01-07 17:28
Thanks @nedtwigg, it works now!

I'm very curious though as to why `build\classes\test` is even being put into `SpotlessTask.target` in the first place, and why [this code](https://github.com/diffplug/spotless/blob/b335462e990f57660b6ecbdaf36a5c8f91b838a9/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java#L147-L158) isn't filtering it out...

**Comment by nedtwigg** [comment] 2017-01-07 20:18
I wonder if perhaps the excludes need to be relativized to the `dir` argument.

**Comment by nedtwigg** [comment] 2017-01-07 21:19
Yup, the excludes need to be relativized.  Added a test to learn this, a rewrote FormatExtension::parse to suit.  1ac94d4129b432a85d916b6b4cdc2148cf1a1f74  Still don't understand how `fileTree()` is intermittently ending up with directories in its input.

**Comment by nedtwigg** [comment] 2017-01-08 02:32
Just published `3.0.0.BETA3`.  I think everything is ready except publishing problems.

Our gradle plugin portal id is `com.diffplug.gradle.spotless`.  Before 3.0, our maven coordinate was `com.diffplug.gradle.spotless:spotless`.  Starting with 3.0, we've moved to `com.diffplug.spotless:spotless-plugin-gradle`.

[Here's the output of the publish](https://travis-ci.org/diffplug/spotless/builds/189906300#L1080-L1087) on travis (no errors), but [our plugin portal page](https://plugins.gradle.org/plugin/com.diffplug.gradle.spotless) is not updated.
[Here's the plugin portal part of build.gradle](https://github.com/diffplug/spotless/blob/3.x/plugin-gradle/build.gradle#L40-L63).
[Here's the rest of the maven publishing build.gradle](https://github.com/diffplug/spotless/blob/3.x/gradle/java-publish.gradle#L67-L147).

Any tips for how we can fix this @oehme?

**Comment by oehme** [comment] 2017-01-08 09:35
If you change coordinates the plugin needs to be approved manually, please leave a message on the plugin portal category of the forum.

**Comment by nedtwigg** [comment] 2017-01-09 23:19
Thanks!  We made it into the plugin portal and maven central.  I've moved my projects and junit over to `3.0.0.RC2` and its much faster, haven't found any regressions.  Merging to master and publishing `3.0.0` shortly.

**Comment by jbduncan** [comment] 2017-01-09 23:25
I've moved my dissertation over to `3.0.0-RC2` as well. Definitely much faster than before!

(This is despite how if it apparently fails to report UP-TO-DATE on specific Spotless subtasks on a second run of `./gradlew build`, and only does so on the 3rd+ run. Why? Who knows! I doubt it really matters, as `./gradlew build --profile` reports virtually no difference in time spent between a 2nd and 3rd run. :stuck_out_tongue_winking_eye:)

**Comment by nedtwigg** [comment] 2017-01-09 23:30
On `build`, eh?  I get that on `spotlessApply`, but not on `spotlessCheck`.  First `spotlessApply` - I changed some files, so it runs.  Second `spotlessApply`, some files were changed by the last call to spotless, so it runs, but doesn't change anything.  Third `spotlessApply` is up-to-date, since nothing has changed since the previous.

**Comment by jbduncan** [comment] 2017-01-09 23:38
> On `build`, eh?

Yep! I find I have to specifically run `build` (oh, now that I test it further, `check` also does this!) rather than just `spotlessCheck` for this strange little inconsistency to pop up.

I suspect the cause is the same as what you explained for `spotlessApply`.

**Comment by nedtwigg** [comment] 2017-01-09 23:53
I'm merging 3.x into master and deleting it, do you have anything else to push @jbduncan?  Also, I think both of us should move back to the PR system starting with 3.x.  The source history has been appropriately messy while we brainstormed, but I think it's time to stabilize.

**Comment by jbduncan** [comment] 2017-01-10 00:01
> I'm merging 3.x into master and deleting it, do you have anything else to push @jbduncan?

Nope, there's nothing else my end, so I'm happy for 3.x to be merged into master now. Thanks for checking. :)

> Also, I think both of us should move back to the PR system starting with 3.x. The source history has been appropriately messy while we brainstormed, but I think it's time to stabilize.

Sounds very sensible to me! I'll happy submit future changes via PRs from now on. :+1:

**Comment by nedtwigg** [comment] 2017-01-10 00:59
It's out!!!  It's finally out!!!!  Submitted a PR to update [junit](https://github.com/junit-team/junit5/pull/626), and updating my personal projects so we can update the examples.

**Closed** 2017-01-20 14:45 UTC
