### ISSUE TITLE
ignoreFailures; show all violations at once

### ISSUE THREAD

**Issue by WebTiger89** [diffplug/spotless#1112] opened 2022-01-24 12:29 UTC
Is it possible to not fail the build when running the spotless*Check task? Currently the task shows only 1 violation. When fixed it shows the next violation.

**Comment by jbduncan** [comment] 2022-01-24 12:58
@WebTiger89 How strange. In my experience, `spotlessCheck` shows the first few errors (not all of them to prevent overwhelming the user).

What happens if you run `spotlessApply`? Does that fix all the errors for you?

**Comment by WebTiger89** [comment] 2022-01-24 13:33
@jbduncan I don't want to let spotless apply fixes. I only use the analyzing part.

**Comment by WebTiger89** [comment] 2022-01-24 13:44
My configuration:
`// Configure spotless
configure<com.diffplug.gradle.spotless.SpotlessExtension> {
    format("misc") {
        // Define the files to apply misc to
        target("*.gradle", "*.md", ".gitignore")

        // Steps to apply to those files
        trimTrailingWhitespace()
        endWithNewline()
    }

    kotlin {
        /*
         * Cover all '.kt' and '.kts` files,
         * by default the target is every '.kt' and '.kts` file in the java sourcesets.
         */
        target("*.kt", "**/src/**/test.gradle.kts")

        // Steps to apply to those files
//        ktfmt("0.30").dropboxStyle()
//        ktlint("0.43.2").userData(mapOf("ignoreFailures" to "true"))
        // It seems diktat applies rule sets from ktlint
//        diktat("1.0.2")
        trimTrailingWhitespace()
        endWithNewline()
    }
}`

When running spotlessCheck the following violations occurs:

> Execution failed for task ':spotlessMiscCheck'.
> The following files had format violations:
      README.md
          @@ -22,4 +22,4 @@
           For�every�precompiled�script�plugin,�a�plugin�marker�is�created.�Those�marker�plugins�do�not�contain�code,
           they�just�have�a�dependency�on�the�actual�plugin�jar.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

As you can see, the check for the kotlin {} format isn't even called. But that's not the only annoying thing.
1. Wtf is this output (above), annyoing shit. What is the problem, can't figure it out
2. When enabling ktlint(), I get an error when running spotlessCheck.

> com.pinterest.ktlint.core.ParseException: 1:1 Expecting a top level declaration
content of 'src\main\kotlin\de\datacollect\test.gradle.kts':
`plugins {
    id("com.github.ben-manes.versions") version "0.41.0"
}
`

Same applies for diktat(). This implies that spotless enables ktlint for diktat?!?! If so, why even use ktlint? Documentation?
3. Where is the fucking documentation. This shit lacks everything
4. Fuck time waster shit plugin
5. sorry

**Comment by jbduncan** [comment] 2022-01-24 14:13
@WebTiger89 I've just tidied up the Spotless code block in your last message to make it easier to read, I hope you don't mind. :)

I'm on a break at work right now, but I might have time to try to reproduce this this evening.

I see you mentioned things in your `build.gradle.kts` file that isn't in your Spotless block above, like a `plugins { id("com.github.ben-manes.versions") version "0.41.0" }` section. Do you have a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) we can use to diagnose this further?

@nedtwigg, any thoughts on this?

@WebTiger89 By the way, have you read the [code of conduct](https://github.com/diffplug/spotless/blob/main/CODE_OF_CONDUCT.md), by any chance? I ask because I see you've used swear words in your last comment, which is something others may take offence to. Though I completely understand - I've felt frustration with third-party software many times!

**Comment by jbduncan** [comment] 2022-01-24 14:23
@WebTiger89 Oh, the reason why it complains about your README.md is because of this part in your Spotless config:

```gradle
    format("misc") {
        // Define the files to apply misc to
        target("*.gradle", "*.md", ".gitignore") // <-- HERE

        // Steps to apply to those files
        trimTrailingWhitespace()
        endWithNewline()
    }
```

The `target` tells Spotless which files to format, and I see it includes "*.md", which means all Markdown files in the same folder as your `build.gradle.kts` file, which includes the README.md.

If you didn't mean to include Markdown files in your formatting, try removing the "*.md" part. Otherwise, then it might be that the `trimTrailingWhitespace()` and `endWithNewline()` steps have found that your README has one or more lines with trailing spaces or it lacks a newline at the end of the file.

I hope this helps!

**Comment by jbduncan** [comment] 2022-01-24 14:26
Oh sorry, I've just seen that you put your `plugins { id("com.github.ben-manes.versions") version "0.41.0" }` code in a separate Kotlin file, not the `build.gradle.kts` one. Apologies!

Regardless, a minimal, reproducible example would be immensely helpful, if you felt up to making one. :)

**Comment by jbduncan** [comment] 2022-01-24 14:32
To answer the query about diktat and ktlint, it looks like diktat [uses ktlint as a framework](https://github.com/analysis-dev/diktat#why-should-i-use-diktat-in-my-cicd), so perhaps that's why diktat applies rulesets from ktlint?

I can't tell from your message if you were just confused by this, or if you didn't want ktlint rulesets to be applied at all, but I hope this helps too.

**Comment by jbduncan** [comment] 2022-01-24 15:43
> ...I might have time to try to reproduce this this evening.

Ah, I've just realised I can't look at this tonight due to a commitment, sorry! Maybe in the future.

**Comment by WebTiger89** [comment] 2022-01-24 18:40
Thanks for your time. I just can't understand why the documentation for most of the analyzer tools is so sparse, not only spotless. You need just a few lines to make everything clear. There isn't even a Quick-Start example for Kotlin DSL.. wtf, do we live in fucking 20 century? Why is there no Kotlin DSL example? There are people that don't contribute to this project and don't know how to use it, so documentation should be based on this level...just few more lines.

And the other problems:
1. no ignore failures. Configurable? Not documented. Makes plugin useless
2. Fails on first error. Why? Not documented. Makes plugin useless
3. What is this output again:

> > The following files had format violations:
      build.gradle.kts
          @@ -59,4 +59,4 @@
           ��������target("*.gradle.kts")
           ��������ktlint()
           ����}
          -}
          +}

How can I know what's wrong? Do I have to guess? Not documented how to read it. Check "detekt" tool to see how it's done properly.
4. ktlint() throws an error -> Expecting a top level declaration. And the file content is just a plugins block.
5. diktat() throws same error as ktlint() -> does diktat apply the same rules like ktlint and therefore fails for the same reason? And when diktat uses ktlint with the same rules under the hood, why eben provide ktlint()?  Or is it for users who want ktlint() but not diktat()?
6. IntelliJ marks the Extensions red: Cannot access class 'com.diffplug.gradle.spotless.KotlinExtension.KotlinFormatExtension'. Check your module classpath for missing or conflicting dependencies. In another project this doesn't happen but I don't know why yet

I will provide an example

**Comment by WebTiger89** [comment] 2022-01-24 19:43
About 6.: I could figure out the cause. When I remove
`implementation("com.diffplug.spotless:spotless-plugin-gradle:6.2.0")`
from dependencies block, red marks disappear.

[configuration-plugin.zip](https://github.com/diffplug/spotless/files/7928378/configuration-plugin.zip)

**Comment by nedtwigg** [comment] 2022-01-25 21:31
> Where is the fucking documentation. This shit lacks everything

Did you see [plugin-gradle/README.md](https://github.com/diffplug/spotless/tree/main/plugin-gradle#quickstart)? We have multiple plugins, so our root `README.md` just links out to the plugins for each build system we support.

I would have blocked you for being aggressive, @jbduncan is much nicer than me, he helped you and offered

> have you read the code of conduct, by any chance? I ask because I see you've used swear words in your last comment, which is something others may take offence to

And you followed up with 

>  do we live in fucking 20 century?

It's unacceptable to treat people who are helping you in this way. My recommendation is to start small - get a small part working, then add more. Or find a different plugin whose authors are happy to get cussed at while they help you for free. I'm gonna block you for a week. Feel free to come back with a calmer tone and one-issue-at-a-time, don't open 4 different issues in a single day, we've got lots of watchers, your questions are duplicates of past questions, and you created a lot of notification spam.

Closing as dupe of #287.

**Closed by nedtwigg** 2022-01-25 21:31 UTC
