### ISSUE TITLE
Could not find spotless-lib-extra-2.30.0.jar

### ISSUE THREAD

**Issue by leungkinghin** [diffplug/spotless#1390] opened 2022-10-31 08:22 UTC
In my own application, we install plugin in gradle as below
```
plugins {
   id 'com.diffplug.spotless' version '6.11.0'
}
```
However when we run gradle command to build the project. Now it prompts the following errors

>  Could not find spotless-lib-extra-2.30.0.jar (com.diffplug.spotless:spotless-lib-extra:2.30.0).
>      Searched in the following locations:
>          https://plugins.gradle.org/m2/com/diffplug/spotless/spotless-lib-extra/2.30.0/spotless-lib-extra-2.30.0.jar

I tried to access the JAR file URL directly in browser and it returns 404 HTTP status, which still worked in last week.
Could you please check if the JAR file can be available in repo again?

**Comment by nedtwigg** [comment] 2022-10-31 08:41
I think this is a bug in the Gradle plugin portal. Lots of builds at DiffPlug just died, with error messages indicating that it's looking for transitives in the now-defunct JCenter but not looking in mavenCentral.

We fixed these problems internally like this:

```gradle
// settings.gradle
pluginManagement {
  repositories {
    gradlePluginPortal()
    mavenCentral()
  }
  ...
```

**Comment by jenschude** [comment] 2022-10-31 10:47
Same issue here. Downgrading to version 6.10.0 and it works. Error only occurs with 6.11.0 for me.

**Comment by leungkinghin** [comment] 2022-10-31 11:06
@nedtwigg Thank you for your suggestion. The library can be accessed after I explicitly assign mavenCentral as secondary artifact repo.

@jenschude I think v6.10.0 works because it uses `spotless-lib-extra with` version < 2.30.0 which are existing in Jcenter.

**Comment by VitaliyKulikov** [comment] 2022-10-31 13:43
just run to fix local cache:
```
$ gradle clean test --refresh-dependencies
```

**Comment by nedtwigg** [comment] 2022-10-31 15:11
@jenschude that's probably because the old version is cached on your machine. Try a blank machine with no cache and I bet both will fail.

**Comment by nedtwigg** [comment] 2022-10-31 15:41
Ah, looks like they figured out the root cause on the gradle forums. JCenter is supposed to 404 on deps that it doesn't have, but it just started timing-out on them instead of 404-ing.

That's why the workaround above to put mavenCentral first fixes the problem.

https://discuss.gradle.org/t/plugin-portal-dependency-resolution-failing-due-to-jcenter-usage/44131/9

As usual, jcenter is a catastrophe.

**Comment by bcmedeiros** [comment] 2022-11-01 01:25
Issue seems to be fixed now, all my failing builds are back.

**Comment by manuth** [comment] 2022-11-01 10:00
I still faced this issue on my laptop while it did not occur on my PC

Running the commend mentioned by @VitaliyKulikov fixed this issue for me.

> ```bash
> gradle clean --refresh-dependencies
> ```

Thank you guys for helping out 😄

**Comment by nedtwigg** [comment] 2022-11-04 15:15
Indeed, a JCenter outage was the root problem, as confirmed by the gradle forum post linked above. Putting `mavenCentral` higher that `gradlePluginPortal` is both a workaround and a future-proof fix.

**Closed by nedtwigg** 2022-11-04 15:15 UTC
Labels: bug
