### ISSUE TITLE
indent is ignored by palantirJavaFormat

### ISSUE THREAD

**Issue by anaconda875** [diffplug/spotless#2204] opened 2024-07-12 07:08 UTC
- Summary of problem: As the title
- Maven version: 3.8
- Spotless version: 2.43.0
- Operating system and version: windows 11
```xml
            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <version>2.43.0</version>
                <configuration>
                    <!-- define a language-specific format -->
                    <java>
                        <!-- no need to specify files, inferred automatically, but you can if you want -->

                        <!-- apply a specific flavor of google-java-format and reflow long strings -->
<!--                        <googleJavaFormat>-->
<!--                            <version>1.20.0</version>-->
<!--                            <style>GOOGLE</style>-->
<!--                            <reflowLongStrings>true</reflowLongStrings>-->
<!--                            <formatJavadoc>false</formatJavadoc>-->
<!--                        </googleJavaFormat>-->
                        <palantirJavaFormat>
                            <version>2.39.0</version>                     <!-- optional -->
                            <style>PALANTIR</style>                       <!-- or AOSP/GOOGLE (optional) -->
                            <formatJavadoc>false</formatJavadoc>          <!-- defaults to false (optional, requires at least Palantir 2.39.0) -->
                        </palantirJavaFormat>
                        <indent>
                            <spaces>true</spaces>
                            <spacesPerTab>2</spacesPerTab>
                        </indent>
                        <importOrder/>
                        <removeUnusedImports/>
                        <formatAnnotations/>
                    </java>
                    <formats>
                        <!-- you can define as many formats as you want, each is independent -->
                        <format>
                            <!-- define the files to apply to -->
                            <includes>
                                <include>src/main/java/**/*.java</include>
                                <include>src/test/java/**/*.java</include>
                            </includes>
                            <!-- define the steps to apply to those files -->
                            <trimTrailingWhitespace/>
                            <endWithNewline/>
                            <indent>
                                <spaces>true</spaces>
                                <spacesPerTab>2</spacesPerTab>
                            </indent>
                        </format>
                    </formats>
                </configuration>
            </plugin>

```

**Comment by anaconda875** [comment] 2024-07-29 11:33
@nedtwigg

**Comment by nedtwigg** [comment] 2024-08-12 00:56
I'm guessing that `palantir` is formatting these as "4 spaces"? The fix is:

- convert spaces to tab, 4
- convert tabs to spaces, 2

Dupe of #794

**Closed by nedtwigg** 2024-08-12 00:56 UTC

**Comment by anaconda875** [comment] 2024-08-12 10:50
> I'm guessing that `palantir` is formatting these as "4 spaces"? The fix is:
> 
>     * convert spaces to tab, 4
> 
>     * convert tabs to spaces, 2
> 
> 
> Dupe of #794

Could you help to point out the exact config that i need to put to my pom.xml?

**Comment by nedtwigg** [comment] 2024-08-12 16:58
It's not polite to `@` a bunch of people, if they want to be involved then they'll subscribe to the issue.

Try this:

```xml
<indent>
  <tabs>true</tabs>
  <spacesPerTab>4</spacesPerTab>
</indent>
<indent>
  <spaces>true</spaces>
  <spacesPerTab>2</spacesPerTab>
</indent>
```
