### ISSUE TITLE
License header ignores skip lines when using git history

### ISSUE THREAD

**Issue by trajano** [diffplug/spotless#2316] opened 2024-10-25 16:14 UTC
If you are submitting a **bug**, please include the following:

- [x] summary of problem

`-DspotlessSetLicenseHeaderYearsFromGitHistory=true` with maven spotless:apply

```
<shell>
                  <includes>
                    <include>**/*.sh</include>
                  </includes>
                  <excludes>
                    <exclude>**/node_modules/**</exclude>
                  </excludes>
                  <trimTrailingWhitespace/>
                  <endWithNewline/>
                  <licenseHeader>
                    <content># (c)$YEAR XXX</content>
                    <skipLinesMatching>^#!/.+?$</skipLinesMatching>
                    <delimiter>[\n]|set</delimiter>
                  </licenseHeader>
</shell>
```

Given an existing file with

```
#!/bin/sh
# (c) 2024 XXXX
set -e
```

updating the file with the retroactive dates drops the shebang

```
# (c) 2000-2024 XXXX
set -e
```

- [x] Gradle or Maven version
maven

- [x] spotless version
2.43.0
- [x] operating system and version
windows
- [ ] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
- [ ] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`

If you're just submitting a feature request or question, no need for the above.

**Comment by nedtwigg** [comment] 2024-10-25 16:36
- Closing as dupe of #2270

**Closed by nedtwigg** 2024-10-25 16:36 UTC
