### ISSUE TITLE
Fork removeUnusedImports() and googleJavaFormat() to support later JLS than the JRE used for the build

### ISSUE THREAD

**Issue by marcphilipp** [diffplug/spotless#713] opened 2020-10-10 15:49 UTC
EDIT by @nedtwigg: summarizing the current situation, easy workaround, and a hard-to-implement potential fix:

If you use `googleJavaFormat()` or `removeUnusedImports()`, and you also use cutting edge java language features such as the Java 15 text blocks, then you must *also* run your build on JRE 15+ (same for language features in any other release, e.g. must use JRE 14+ to use Java 14 language features, etc.). This is because `google-java-format` selects which JLS specification to use based on which version of JVM it is running on.

The easy solution is to run your build with a JVM at least as new as the code you are formatting. The hard solution is to add a feature to Spotless which allows forking a more modern JVM just to run formatting.  Happy to take a PR for this feature, but we have no plans to implement the feature ourselves.

-------

When trying to use `removeUnusedImports` with a Java file that contains a Java 15 text block, the following exception is thrown:
https://ge.junit.org/s/5jcvukwcdcckg/console-log?task=:junit-jupiter-engine:spotlessJava

Config:
https://github.com/junit-team/junit5/blob/4dd6981ece3a5d5275844ba6d9b4fa7ab60bf0af/build.gradle.kts#L134-L154

**Comment by sormuras** [comment] 2020-10-10 16:14
I guess, an outdated GJF is bundled. Perhaps an upgrade to 1.9 does help?

https://github.com/google/google-java-format/releases

**Comment by jbduncan** [comment] 2020-10-10 20:07
When using the `googleJavaFormat()` step, by default we import 1.7 if the JDK that Spotless is running on is JDK >=8, or 1.9 if it's JDK >=11. This is because GJF 1.8+ now requires JDK 11. However, I don't know how we deal with `removeUnusedImports()`, as I don't have an IDE in front of me at the moment...

@nedtwigg Do you happen to know which version we use for `removeUnusedImports()`? Regardless, I can think of a few potential fixes:
- Import GJF 1.7/1.9 depending on the JDK
- Allow the user to choose which version of GJF to use
- Find an alternative to GJF that's Java 8-compatible. Maybe Eclipse has something here? But I recall @fvgh saying that it requires JDK 11 now...

Any thoughts on this?

**Comment by nedtwigg** [comment] 2020-10-10 20:18
We do use the latest 1.9 when run on Java 11+. But, gjf picks formatting rules based on the JVM it's running on. So if you want to format Java 15 constructs, you need to run the build on Java 15.

**Comment by marcphilipp** [comment] 2020-10-11 06:54
Does gjf run in the build VM or a forked one?

**Comment by nedtwigg** [comment] 2020-10-11 07:02
The build VM. Not forked. Happy to take a PR which adds that feature though.

**Comment by marcphilipp** [comment] 2020-10-11 07:07
For the time being, I made it optional depending on the Java version the build is running on.

**Comment by nedtwigg** [comment] 2020-10-22 02:33
This issue was first, but I'm going to close it as a dupe of #724, because that issue is more general-purpose.

**Closed by nedtwigg** 2020-10-22 02:33 UTC
Labels: enhancement
