### ISSUE TITLE
No such reference 'origin/main'

### ISSUE THREAD

**Issue by fullstackctp** [diffplug/spotless#1876] opened 2023-11-06 12:42 UTC
I am getting this proplem with my springboot project after applying spotless.It builds in local.
Could not determine the dependencies of task ':exchange-api:spotlessCheck'.
> Could not create task ':exchange-api:spotlessMiscCheck'.
   > Could not create task ':exchange-api:spotlessMisc'.
      > No such reference 'origin/main'

I don't use gitlab . 
I am using Space by jetspace as my repositorty

**Comment by fullstackctp** [comment] 2023-11-14 11:18
HI is there any response on this ?

**Comment by nedtwigg** [comment] 2023-11-16 17:15
Dupe of https://github.com/diffplug/spotless/issues/710

**Closed by nedtwigg** 2023-11-16 17:15 UTC
