### ISSUE TITLE
GoogleJavaFormat entry point does not sort imports or remove unused

### ISSUE THREAD

**Issue by sormuras** [diffplug/spotless#48] opened 2016-11-01 22:49 UTC
The current entry point in [spotless/java/GoogleJavaFormat](https://github.com/diffplug/spotless/blob/master/src/main/java/com/diffplug/gradle/spotless/java/GoogleJavaFormat.java) is the `Formatter.formatSource` method which lacks fixing of import order and removal of unused imports.

If the entry point was changed to [Main.main](https://github.com/google/google-java-format/blob/master/core/src/main/java/com/google/googlejavaformat/java/Main.java), the `googleJavaFormat()` step would work as expected.

#28 would partly be solved - if one uses `googleJavaFormat()`

**Comment by nedtwigg** [comment] 2016-11-01 23:17
Looks like main calls [FormatFileCallable](https://github.com/google/google-java-format/blob/master/core/src/main/java/com/google/googlejavaformat/java/FormatFileCallable.java).

Here's an excerpt:

```java
  @Override
  public String call() throws FormatterException {
    if (parameters.fixImportsOnly()) {
      return fixImports(input);
    }

    String formatted =
        new Formatter(options).formatSource(input, characterRanges(input).asRanges());
    formatted = fixImports(formatted);
    return formatted;
  }

  private String fixImports(String input) throws FormatterException {
    input =
        RemoveUnusedImports.removeUnusedImports(
            input,
            parameters.removeJavadocOnlyImports()
                ? JavadocOnlyImports.REMOVE
                : JavadocOnlyImports.KEEP);
    input = ImportOrderer.reorderImports(input);
    return input;
  }
```

Which points us to this gem in [RemoveUnusedImports](https://github.com/google/google-java-format/blob/master/core/src/main/java/com/google/googlejavaformat/java/RemoveUnusedImports.java):

`public static String removeUnusedImports(String contents, JavadocOnlyImplorts)` 

So two action items:

1. It looks like our `google-java-format` is missing some key pieces, and adding them will change the formatting of files to what users actually expect.
2. We can use removeUnusedImports from google-java-format for the other import ordering step as well.

Here's the tricky bit.  Right now, spotless has built-in support for the eclipse formatter (we bundle the necessary class files).  google-java-format also uses these eclipse libraries, but uses older ones.  To keep the different versions separate, we have to do some classloader gymnastics:

That's the reason why we interact with google-java-format in such a strange way:
https://github.com/diffplug/spotless/blob/master/src/main/java/com/diffplug/gradle/spotless/java/GoogleJavaFormat.java

So, in order to call these methods, we'll have to do more classloader magic.  Difficult, but not impossible.

**Comment by sormuras** [comment] 2016-11-02 09:49
Maybe, item 1. can partly be resolved over at google-java-format -- see referenced issue above. It it gets merged, the new entry point in `Formatter` can be used without doing too much classloader magic.

**Comment by jbduncan** [comment] 2017-01-05 20:28
I see that a fix has been implemented in https://github.com/diffplug/spotless/commit/44b7830cf92a1e27ede0d2d301bd579b12aec22b and https://github.com/diffplug/spotless/commit/75392f87897cf8f208ebc2f6feca8b206aa3cd60. Well done @nedtwigg!

Have you confirmed that it works with google-java-format-1.0? I believe that 1.0 may not have functionality for reordering imports and removing unused ones.

**Comment by nedtwigg** [comment] 2017-01-05 21:05
Haven't confirmed, but I'm fine with setting 1.1 as the lowest supported release.

**Comment by jbduncan** [comment] 2017-01-05 21:27
Sounds like a plan to me!

I'm personally happy for this issue to be closed now, but I wonder if @sormuras has any other thoughts before we do so?

**Comment by nedtwigg** [comment] 2017-01-05 22:08
I like to close things with "Released in 3.0.0", and we've still got a few loose-ends before we get there, I think :)

**Comment by nedtwigg** [comment] 2017-01-06 02:01
Fixed in 3.0.0.BETA2 #63

**Closed by nedtwigg** 2017-01-06 02:01 UTC
Labels: bug

**Comment by 243826** [comment] 2020-01-06 22:57
How does it work?

I have these imports... 
```
import java.io.IOException;
import java.security.KeyPair;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;

import javax.validation.constraints.NotNull;

import com.xxx.common.DAM;

```

they get reformatted as

```
import com.xxx.common.DAM;
import java.io.IOException;
import java.security.KeyPair;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import javax.validation.constraints.NotNull;
```

with the following mvn config:

```
            <plugin>
              <groupId>com.diffplug.spotless</groupId>
              <artifactId>spotless-maven-plugin</artifactId>
              <version>1.27.0</version>
              <configuration>
                <java>
                  <licenseHeader>
                    <file>${basedir}/toolsettings/license-header</file>
                  </licenseHeader>
                  <googleJavaFormat>
                    <version>1.7</version>
                  </googleJavaFormat>
                  <removeUnusedImports />
                </java>
                <importOrder>
                  <order>java,javax,org,com,com.cisco,com.xxx,com.xxx.common</order>
                </importOrder>
              </configuration>
            </plugin>
```

Obviously, not what I intended. Could someone comment what am I doing wrong?

**Comment by nedtwigg** [comment] 2020-01-07 04:26
I think the `<importOrder></...>` should be inside the `<java>...</java>` part.  See [this example](https://github.com/diffplug/spotless/tree/master/plugin-maven#applying-to-java-source).

**Comment by 243826** [comment] 2020-01-07 05:40
Thank you! It worked and note to myself to be a little more thorough :-)
