### ISSUE TITLE
No such reference 'origin/main' error in github action

### ISSUE THREAD

**Issue by leungkinghin-ct** [diffplug/spotless#2371] opened 2024-12-20 18:22 UTC
When i run spotless command in github action, it throws error as below. Could you please check why it would happen and how it can be resolved? Thank you.

```
Error:  Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.43.0:check (default-cli) on project subscriptions-tracker: Execution default-cli of goal com.diffplug.spotless:spotless-maven-plugin:2.43.0:check failed: No such reference 'origin/main' -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
Error: Process completed with exit code 1.
```

Following is my github action yaml file

```
name: Continuous Integration Pipeline


on: [push]

jobs:
  checks:
    name: Code Checking
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: 'maven'
      - name: Clean and Build with Maven
        run: mvn clean && mvn install
      - name: Code Formatting
        run: mvn --batch-mode --no-transfer-progress spotless:check
```

Maven version : 4.0.0
spotless version : 2.43.0

**Comment by nedtwigg** [comment] 2024-12-21 04:05
Dupe of #710

**Closed** 2024-12-21 04:05 UTC
