### ISSUE TITLE
Gradle: can't targetExclude files in the buildDir

### ISSUE THREAD

**Issue by tbroyer** [diffplug/spotless#399] opened 2019-05-08 17:52 UTC
I have a project where some Java source files are generated by a task; they're generated into `build/generated-sources/` and added to a source set to later be compiled (like any other source files). I don't want those generated source files to be checked, but setting `targetExclude("build/generated-sources/**/*.java")` doesn't work.

This is using Gradle 5.4.1 and Spotless 3.23.0 on Linux.

The way `java()` works, `target` is set to include `allJava` sources for all source sets, irrespective of their location (contrary to setting the target to an Ant-style pattern, which will exclude files in the `buildDir`).
The problem is that `targetExclude()` works the same as `target()` and will also exclude the `buildDir`, so `targetExclude("build/generated-sources/**/*.java")` will result in an empty `FileTree`, and my generated sources will be checked by Spotless.

I found a workaround by using a `FileTree`, which won't go through that code that excludes the `buildDir`:
```kotlin
targetExclude(fileTree("$buildDir/generated-sources") { include("**/*.java") })
```
But the special exclusions should only be applied to the `target`, not `targetExclude`.

To reproduce, no need for a task generating source code: put some malformed Java source file somewhere in the `buildDir` (e.g. `$buildDir/generated-sources/test/Foo.java`) and include it in a source set:
```gradle
sourceSets {
  test {
    java {
      srcDir("$buildDir/generated-sources/test")
    }
  }
}
spotless {
  java {
    targetExclude("build/generated-sources/**/*.java")
    googleJavaFormat()
  }
}
```

**Comment by nedtwigg** [comment] 2019-05-08 18:09
Hmmm... so `JavaExtension` sets the target automatically like this:

https://github.com/diffplug/spotless/blob/9843130704d0eb926ee5127ce241b0b158c6a5f9/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/JavaExtension.java#L176-L198

And then calls super, which is this:

https://github.com/diffplug/spotless/blob/9843130704d0eb926ee5127ce241b0b158c6a5f9/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java#L569-L581

So the exclusion should still happen.  The reason it's failing is that `targetExclude` goes through `parseTargets`:

https://github.com/diffplug/spotless/blob/9843130704d0eb926ee5127ce241b0b158c6a5f9/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java#L152-L154

Which excludes `.git` and `build/` and stuff like that:

https://github.com/diffplug/spotless/blob/9843130704d0eb926ee5127ce241b0b158c6a5f9/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java#L190-L201

This is good when we're parsing targets, e.g. `target('**/*.ext')` is much slower if you're slogging through the `.git` and `build/` directories.  But it's bad for cases like this.

By supplying a `fileTree`, you're bypassing the parsing, which is why the workaround works.

The complicated parse logic is pretty nasty, and has caused surprises before.  But there are lots of wildcard `**/*.ext` inclusions in the wild, which are also nasty, but useful to our users, and those perform terribly without these exclusions.

Maybe a good way to handle this would be if those complicated exclusions only happened if `target.startsWith('**/')`.  Otherwise, no fancy excludes, and the target string is passed straight.

**Comment by tbroyer** [comment] 2019-05-08 20:13
How about passing a boolean to `parseTargets` and down to `parseTarget` to turn those special exclusions on/off? `target` would call `parseTargets(true, targets)`, and `targetExclude` would call `parseTargets(false, targets)`. Call that boolean `addSpecialExcludes`, or `isInclude`.

**Comment by nedtwigg** [comment] 2019-05-08 21:08
That could work too.  I think the first proposal is closer to the root cause, and the second proposal is a bit more of a patch.

The root cause is that the parsing logic assumes the user was lazy, and didn't really mean to include `build` or `.git` or subprojects.  And the bug is that if you weren't lazy, it's really surprising that the tool stops doing what its docs say that it will do.  So I think the rootcause fix is "only assume the user is lazy if the user actually was lazy".

Can we think of a String where the change I have proposed would be a problem for an existing target?  The only one I can think of is `subprojectdir/**/*.ext`.  Right now, we automatically exclude the `subprojectdir/build`, and after my proposed change, we wouldn't.  That would be pretty strange usage though, to apply spotless to the root project, and then apply it specifically to a single subproject...  It's easy to fix, and the change would fail by applying to too much rather than too little, so it "fails safe".

**Comment by tbroyer** [comment] 2019-05-08 22:02
I agree for `target("**/*.ext")`, but still can't find a single argument for `targetExclude("**/*.ext")` not actually excluding the build dirs. Why would you want `targetExclude("**/*.ext")` to mean "exclude all files whose name ends in `*.ext` **except** those files in the build dir?

For example, `kotlin` includes all `*.kt` and `*.kts` but I've had issues with `*.kts` files "missing a top level declaration" (haven't had time to investigate). In case some of those files were similarly generated in the build dir, `targetExclude("**/*.kts")` would **not** actually exclude them.

**Comment by nedtwigg** [comment] 2019-05-08 23:35
> Why would you want targetExclude("**/*.ext") to mean "exclude all files whose name ends in *.ext except those files in the build dir?

For the hypothetical buildscript where I did `targetExclude('**/*.ext')`, what was the `target()`?  It seems the result would be empty no matter what target was...  But I see your point.  Probably we should do both - and only exclude if `isInclude=true` and `pattern.startsWith('**/')`.

**Comment by redhead** [comment] 2019-06-24 18:41
is there any workaround how to currently exclude generated sources?

**Comment by tbroyer** [comment] 2019-06-24 18:48
@redhead Yes, given in the original report above. `Ctrl`+`F` workar

**Comment by nedtwigg** [comment] 2019-10-03 18:34
Resolved by https://github.com/diffplug/spotless/pull/457 and released in `3.24.3`.

**Closed by nedtwigg** 2019-10-03 18:34 UTC
Labels: bug

**Comment by niels1voo** [comment] 2022-04-06 18:21
I tried to use the OP's original non-working solution, thinking that #457 would make it work, but no luck.
`targetExclude("build/*generated-sources/**/*.java")`
results in 
'Execution failed for task ':helium-data-model:spotlessJava'.
> Spotless error! All target files must be within the project dir.
    project dir: /Users/niels/repo/sx/helium/helium-main/helium-data-model
         target: /Users/niels/repo/sx/helium/helium-main/build/helium-data-model/generated/sources/xjc/java/com/soundexchange/helium/distribution/iso20022/NameAndAddress3.java
'
I'm using gradle spotlees plugin 6.4.2

**Comment by niels1voo** [comment] 2022-04-06 19:05
`targetExclude "${projectDir}/build/*/generated/sources/**/*.java"` 
this works...need to use the project directory.

**Comment by niels1voo** [comment] 2022-04-06 21:53
I stepped through the build in a debugger and found that the problem lies in SpotlessTaskImpl.getOutputFile().  The call to FormatExtension.relativize returns null, which causes the exception to be thrown. relativize returns null because the targetExclude is not a child of the subproject directory in a multi-module build.  So targetExclude can't be used to exclude generated sources from a multi-module build, because the build output is at the root directory, not the subproject directory.

**Comment by twarner-sofi** [comment] 2022-06-29 19:58
Did this regress? I cannot get targetExclude to work at all. Neither `targetExclude("build/generated/**/*.java")` nor `targetExclude(fileTree("build/generated") { include("**/*.java") })` work for me. Is there another recommended way to exclude files in buildDir?

I will try to come up with a minimal repro when I have time.
