### ISSUE TITLE
How to decrease indent level?

### ISSUE THREAD

**Issue by noel-yap** [diffplug/spotless#646] opened 2020-07-14 18:17 UTC
https://stackoverflow.com/questions/62901157/how-to-decrease-indent-level-in-spotless

I'm using the following in my `build.gradle`:

```
plugins {
  id 'com.diffplug.gradle.spotless' version '4.5.1'
}

spotless {
  java {
    googleJavaFormat()

    replaceRegex 'Combine function call with lambda.', '(\\.[A-Za-z][0-9A-Za-z]+\\()\\n\\s+', '$1'
  }
```

This reformats the following code:

```
.flatMap(
    t2 -> {
      …
    }));
```

to:

```
.flatMap(t2 -> {
      …
    }));
```

What needs to be done so the indent level is decreased such that it reformats to:

```
.flatMap(t2 -> {
  …
}));
```

**Comment by noel-yap** [comment] 2020-07-14 19:41
Actually, I'm noticing a bug in `googleJavaFormat()` such what should be formatted as:

```
Array.of(
    …);
```

is being formatted as:
```
        …);
```

**Comment by nedtwigg** [comment] 2020-07-14 20:59
Dupe of #647.

**Closed by nedtwigg** 2020-07-14 20:59 UTC
Labels: question
