### ISSUE TITLE
Proper usage of KotlinScript Gradle

### ISSUE THREAD

**Issue by ColtonIdle** [diffplug/spotless#866] opened 2021-05-08 22:04 UTC
The docs say:

```
spotless { // if you are using build.gradle.kts, instead of 'spotless {' use:
           // configure<com.diffplug.gradle.spotless.SpotlessExtension> {
```

so it's suggesting to use `configure<com.diffplug.gradle.spotless.SpotlessExtension> ` with a kts file, but I used `spotless {` instead and it works just fine. Is there any reason we would use `configure<com.diffplug.gradle.spotless.SpotlessExtension>`?

**Comment by ciscoo** [comment] 2021-05-15 01:54
> Is there any reason we would use configure<com.diffplug.gradle.spotless.SpotlessExtension>?

You would use the latter when [type-safe model accessors are not available](https://docs.gradle.org/current/userguide/kotlin_dsl.html#sec:kotlin_using_standard_api).

**Comment by nedtwigg** [comment] 2021-06-15 23:16
Closing as dupe of #858.

**Closed by nedtwigg** 2021-06-15 23:16 UTC
Labels: question
