### ISSUE TITLE
Allow enabling custom rulesets via a subproject module {feature request / question}

### ISSUE THREAD

**Issue by ragdroid** [diffplug/spotless#2005] opened 2024-01-17 07:36 UTC
## Summary of problem
We use custom ktlint rules in our codebase according to this sample provided in the ktlint [documentation](https://pinterest.github.io/ktlint/latest/api/custom-rule-set/#ktlint-ruleset-template). These rules are a part of our repository as a subproject. 

Recently, support to pull-in custom ktlint rules was added but only as a [maven dependency](https://github.com/diffplug/spotless/issues/1220) 

## Question
Is there a way to pull-in custom ktlint rules from a subproject? 

If not, could we add it as a feature?

## Spotless Version
Spotless 6.24.0

- [x] summary of problem
- [x] Gradle or Maven version
- [x] spotless version
- [ ] operating system and version
- [ ] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
- [ ] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`

**Comment by Goooler** [comment] 2024-01-17 11:28
Duplicate of #1901

**Closed by Goooler** 2024-01-17 11:28 UTC
