### ISSUE TITLE
Support for Gradle Java Toolchains

### ISSUE THREAD

**Issue by sihutch** [diffplug/spotless#2211] opened 2024-07-29 14:10 UTC
Gradle version: 7.6.4
Spotless version: 6.21.0
Java version: Coretto 17.0.11
Operating system and version: Mac OS 14.5 

The Spotless Gradle Plugin does not support [Gradle Java Toolchains](https://docs.gradle.org/7.6.4/userguide/toolchains.html)

If Gradle is run on a Java 17 JDK. But we compile/test Java 21 code using the following toolchain configuration

```groovy
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}
```
Gradle can compile the Java 21 code but the Spotless Gradle Plugin does not use the toolchain JDK and fails with an exception when executing 

```shell
./gradlew clean spotlessCheck
```

I have created a [basic project ](https://github.com/sihutch/spotless-toolchains?tab=readme-ov-file) with steps to recreate the problem.

Do you have any plans to support Java Toolchains?

**Comment by Goooler** [comment] 2024-07-31 01:13
See https://github.com/google/google-java-format/issues/1125.

**Comment by mr-serjey** [comment] 2024-08-01 10:17
Hi @Goooler, this issue is relevant for my project as well and I feel that I could contribute to fix the issue. But before I start working on PR, I wanted to make sure that implementation idea is viable...

The idea is to:

1. Make [FormatExtension.lazyActions](https://github.com/diffplug/spotless/blob/b6d71e75434f3b5d6199295adc4373cf9168b865/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/SpotlessExtensionImpl.java#L66-L67) aware of Gradle Jvm toolchain configuration.
    - First option is to execute these lazy actions using the [Worker API](https://docs.gradle.org/current/userguide/worker_api.html) with [process isolation](https://docs.gradle.org/current/userguide/worker_api.html#isolation-modes) and [Gradle Jvm toolchain](https://docs.gradle.org/current/userguide/toolchains.html#sec:plugins_toolchains) configuration.
    - Alternative option is to iterate upon the [defaultVersion() concept](https://github.com/search?q=repo%3Adiffplug%2Fspotless+%22.defaultVersion%28%29%22+language%3AJava&type=code&l=Java) and fix it in such a way that the [Jvm.Support class](https://github.com/diffplug/spotless/blob/2cf1fa536bc497b4e446855d5b47da0cfbac67e4/lib/src/main/java/com/diffplug/spotless/java/GoogleJavaFormatStep.java#L94) would respect Gradle Jvm toolchain configuration instead of simply relying on [`java.version`](https://github.com/diffplug/spotless/blob/aa1a6665ef08b7c93bfa3fd745ecb67b0631771a/lib/src/main/java/com/diffplug/spotless/Jvm.java#L39) system property.  

2. Migrate [SpotlessTaskImpl](https://github.com/diffplug/spotless/blob/748ef4107cd6b36b9ce7a12690939c093364368a/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/SpotlessTaskImpl.java#L68) to execute operations via Worker API (again with process isolation and with respect of toolchain configuration)

@Goooler, please let me know what you think about it and if you have any suggestions.

**Comment by aciccarello** [comment] 2024-08-01 20:25
Looks like this might be a duplicate of #724

**Comment by Goooler** [comment] 2024-08-06 06:31
@mr-serjey Thanks for your response! I would prefer the second. WDYT? @nedtwigg

**Comment by nedtwigg** [comment] 2024-08-12 00:43
Correct, this is a dupe of #724, even though this issue has the better discussion, I'm going to close this one so that watchers of the original issue will get notified if something gets merged.

I don't have a preference for 1 vs 2, so I defer to the implementor and I think @Goooler has good insight that option `2` is probably easier. But I think that migrating the `defaultVersion()` concept in the `Jvm.Support` class is non-optional, the user experience will be poor without it.

**Closed by nedtwigg** 2024-08-12 00:43 UTC
Labels: enhancement
