### ISSUE TITLE
problems running prettier

### ISSUE THREAD

**Issue by xenoterracide** [diffplug/spotless#886] opened 2021-07-08 15:41 UTC
prettier is erroring, I've gotten 2 different errors, one without the config specified and one with

here's the tree

```
* What went wrong:
Execution failed for task ':user:model:spotlessJava'.
> Unexpected response status code at /prettier/format [HTTP 501] -- (Error while formatting: Error: No parser could be inferred for file: AuthnIdentity.java)
```

my config which is in a `buildSrc` kotlin plugin

```kt
spotless {
  ratchetFrom = "HEAD"
  java {
    removeUnusedImports()
    licenseHeader(
      String.format(
        "/*%n" +
          " * $copyright%n" +
          " * $license%n" +
          " * $licenseSimple%n" +
          " */%n"
      )
    )
    prettier()
  }
}
```

how I installed prettier

```sh
yarn add --dev prettier prettier-plugin-java 
❯ yarn --version                                                                                                                            # backend -> master + ? ! »
2.4.2
❯ yarn info prettier                                                                                                                        # backend -> master + ? ! »
└─ prettier@npm:2.3.2
   ├─ Version: 2.3.2
   │
   └─ Exported Binaries
      └─ prettier
└─ prettier-plugin-java@npm:1.3.0
   ├─ Version: 1.3.0
   │
   └─ Dependencies
      ├─ java-parser@npm:1.2.0 → npm:1.2.0
      ├─ lodash@npm:4.17.21 → npm:4.17.21
      └─ prettier@npm:2.3.1 → npm:2.3.1
```

```
❯ ./gradlew --version                                                                                                                       # backend -> master + ? ! »

------------------------------------------------------------
Gradle 7.1.1
------------------------------------------------------------

Build time:   2021-07-02 12:16:43 UTC
Revision:     774525a055494e0ece39f522ac7ad17498ce032c

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.11 (AdoptOpenJDK 11.0.11+9)
OS:           Linux 5.10.42-1-MANJARO amd64
```

```properties
com.diffplug.durian:durian-collect:1.2.0=runtimeClasspath
com.diffplug.durian:durian-core:1.2.0=runtimeClasspath
com.diffplug.durian:durian-io:1.2.0=runtimeClasspath
com.diffplug.spotless:spotless-lib-extra:2.15.1=compileClasspath,runtimeClasspath
com.diffplug.spotless:spotless-lib:2.15.1=compileClasspath,runtimeClasspath
com.diffplug.spotless:spotless-plugin-gradle:5.14.1=compileClasspath,runtimeClasspath
```

you can essentially look at https://github.com/xenoterracide/iw-ppm-backend but there have been some updates locally

**Comment by xenoterracide** [comment] 2021-07-08 16:44
ok, I think I tracked this down, it's actually a problem with prettier, might be good to apply the plugin automagically directly instead of thinking the prettier will do it

https://github.com/prettier/prettier/issues/11177

**Comment by nedtwigg** [comment] 2021-07-08 21:15
Closing as dupe of #888

**Closed by nedtwigg** 2021-07-08 21:15 UTC
Labels: question
