### ISSUE TITLE
License header for shell

### ISSUE THREAD

**Issue by xenoterracide** [diffplug/spotless#2062] opened 2024-03-06 18:30 UTC
title says it all? in this case of course it has to go "after" the shebang `#!/..` line

**Comment by trajano** [comment] 2024-10-25 16:12
```
<shell>
                  <includes>
                    <include>**/*.sh</include>
                  </includes>
                  <excludes>
                    <exclude>**/node_modules/**</exclude>
                  </excludes>
                  <trimTrailingWhitespace/>
                  <endWithNewline/>
                  <licenseHeader>
                    <content># (c)$YEAR .... blah....</content>
                    <skipLinesMatching>^#!/.+?$</skipLinesMatching>
                    <delimiter>[\n]|set</delimiter>
                  </licenseHeader>
                </shell>
```

But this will require your shell scripts to start with a blank line or `set` after the `#!/`

This won't work correctly with ` -DspotlessSetLicenseHeaderYearsFromGitHistory=true` though

**Comment by nedtwigg** [comment] 2024-10-25 16:34
This is the OG issue, but closing as dupe of #2316 since it has more detailed repro

**Closed by nedtwigg** 2024-10-25 16:34 UTC

**Comment by nedtwigg** [comment] 2024-10-25 16:36
Actually, go to https://github.com/diffplug/spotless/issues/2270, seems like the root cause may have been identified there.
