### ISSUE TITLE
Gradle build issue with Eclipse formatter

### ISSUE THREAD

**Issue by gokul-reddy-muddarla** [diffplug/spotless#1692] opened 2023-04-28 23:57 UTC
I am integrating `spotless` to my spring boot project. Version = "6.18.0"
Gradle version: 6.8.3

In build.gradle I add something like below:

```
plugins {
    id "com.diffplug.spotless" version "6.18.0"
}

subprojects {
apply plugin: 'com.diffplug.spotless'
    spotless {
        groovyGradle {
            target '**/*.gradle'
        }

        format 'misc', {
            target '**/*.md', '**/.gitignore'
            trimTrailingWhitespace()
            indentWithTabs()
            endWithNewline()
        }

        java {
            indentWithTabs()
            endWithNewline()
            removeUnusedImports()
            // Using google/palantir formatter has NO issues, only issue with below eclipse formatter
            eclipse('4.26').configFile(rootDir.path + '/config/eclipse.xml')
            importOrder('lombok', 'java|javax', 'org', 'net', 'io', 'com', '', '\\#') //# is the static import
        }
    }
}
```

And i see the following error:
```
Could not determine the dependencies of task ':my-module:spotlessCheck'.
14:23:23  > Could not create task ':my-module:spotlessJavaCheck'.
14:23:23     > Could not create task ':my-module:spotlessJava'.
14:23:23        > javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
```

Q. Why is this only with Eclipse Formatter?
Q. What is possible solution ?

**Comment by gokul-reddy-muddarla** [comment] 2023-04-29 00:26
More debug logs:

```
17:13:22  2023-04-29T00:13:22.498+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
17:13:22  2023-04-29T00:13:22.498+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at dev.equo.solstice.p2.Unchecked.wrap(Unchecked.java:25)
17:13:22  2023-04-29T00:13:22.498+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at dev.equo.solstice.p2.P2Model.query(P2Model.java:133)
17:13:22  2023-04-29T00:13:22.498+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.diffplug.spotless.extra.EquoBasedStepBuilder.get(EquoBasedStepBuilder.java:103)
17:13:22  2023-04-29T00:13:22.498+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.diffplug.spotless.FormatterStepImpl.calculateState(FormatterStepImpl.java:58)
17:13:22  2023-04-29T00:13:22.498+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.diffplug.spotless.LazyForwardingEquality.state(LazyForwardingEquality.java:56)
17:13:22  2023-04-29T00:13:22.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.diffplug.spotless.LazyForwardingEquality.unlazy(LazyForwardingEquality.java:118)
17:13:22  2023-04-29T00:13:22.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.diffplug.spotless.LazyForwardingEquality.unlazy(LazyForwardingEquality.java:124)
17:13:22  2023-04-29T00:13:22.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.diffplug.gradle.spotless.JvmLocalCache$LiveCacheKeyImpl.set(JvmLocalCache.java:60)
17:13:22  2023-04-29T00:13:22.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.diffplug.gradle.spotless.SpotlessTask.setSteps(SpotlessTask.java:168)
17:13:22  2023-04-29T00:13:22.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.diffplug.gradle.spotless.SpotlessTaskImpl_Decorated.setSteps(Unknown Source)
17:13:22  2023-04-29T00:13:22.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.diffplug.gradle.spotless.FormatExtension.setupTask(FormatExtension.java:824)
17:13:22  2023-04-29T00:13:22.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.diffplug.gradle.spotless.JavaExtension.setupTask(JavaExtension.java:391)
17:13:22  2023-04-29T00:13:22.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.diffplug.gradle.spotless.SpotlessExtensionImpl.lambda$createFormatTasks$6(SpotlessExtensionImpl.java:70)
17:13:22  2023-04-29T00:13:22.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.DefaultMutationGuard$2.execute(DefaultMutationGuard.java:44)
17:13:22  2023-04-29T00:13:22.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.DefaultMutationGuard$2.execute(DefaultMutationGuard.java:44)
17:13:22  2023-04-29T00:13:22.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:100)
17:13:22  2023-04-29T00:13:22.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:95)
17:13:22  2023-04-29T00:13:22.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
17:13:22  2023-04-29T00:13:22.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
17:13:22  2023-04-29T00:13:22.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
17:13:22  2023-04-29T00:13:22.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
17:13:22  2023-04-29T00:13:22.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
17:13:22  2023-04-29T00:13:22.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
17:13:22  2023-04-29T00:13:22.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
17:13:22  2023-04-29T00:13:22.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:71)
17:13:22  2023-04-29T00:13:22.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
17:13:22  2023-04-29T00:13:22.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:71)
17:13:22  2023-04-29T00:13:22.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:92)
17:13:22  2023-04-29T00:13:22.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.ImmutableActionSet$SetWithManyActions.execute(ImmutableActionSet.java:329)
17:13:22  2023-04-29T00:13:22.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:264)
17:13:22  2023-04-29T00:13:22.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.DefaultNamedDomainObjectCollection.doAdd(DefaultNamedDomainObjectCollection.java:113)
17:13:22  2023-04-29T00:13:22.499+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:258)
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.DefaultNamedDomainObjectCollection$AbstractDomainObjectCreatingProvider.tryCreate(DefaultNamedDomainObjectCollection.java:944)
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	... 174 more
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at dev.equo.solstice.p2.P2Client.getBytes(P2Client.java:145)
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at dev.equo.solstice.p2.P2Client.getString(P2Client.java:116)
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at dev.equo.solstice.p2.P2Client$Folder.<init>(P2Client.java:209)
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at dev.equo.solstice.p2.P2Client.addUnits(P2Client.java:94)
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at dev.equo.solstice.p2.P2Session.populateFrom(P2Session.java:34)
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at dev.equo.solstice.p2.P2Model.queryRaw(P2Model.java:96)
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at dev.equo.solstice.p2.P2Model.query(P2Model.java:125)
17:13:22  2023-04-29T00:13:22.500+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	... 205 more
17:13:22  2023-04-29T00:13:22.501+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.io.EOFException: SSL peer shut down incorrectly
17:13:22  2023-04-29T00:13:22.501+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	... 229 more
17:13:22  2023-04-29T00:13:22.501+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
17:13:22  2023-04-29T00:13:22.501+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
```

**Comment by alok-runner** [comment] 2023-07-18 12:16
I've seen this as well, the only workaround i've ever found was to stay on 6.16.0 before the p2 changes

**Comment by nedtwigg** [comment] 2024-01-15 00:07
- Dupe of #1658

**Closed by nedtwigg** 2024-01-15 00:07 UTC
Labels: bug-unconfirmed
