### ISSUE TITLE
Is there a max error print on error limit?

### ISSUE THREAD

**Issue by shawnthye** [diffplug/spotless#991] opened 2021-11-09 18:50 UTC
Hi, quick question, I hope its is not a slow one

I am using spotless for `ktlint`, Is there a way that we can print out all the error for all file before it exist?

currently seem like a cap there? 

for example, my project has more than 300 files that contains `max-line-length` error, but **SpotlessCheck** only give me few of them at a time.

**Comment by nedtwigg** [comment] 2021-11-09 18:59
Dupe of #287

**Closed by nedtwigg** 2021-11-09 18:59 UTC
