### ISSUE TITLE
Dependencies required by Gradle plugin 6.11.0 cannot be found in repos

### ISSUE THREAD

**Issue by davidburstrom** [diffplug/spotless#1320] opened 2022-09-14 10:57 UTC
Trying to bump to `com.diffplug.spotless:spotless-plugin-gradle:6.11.0`, the spotless-lib and spotless-lib-extra cannot be resolved. The versions required by 6.10.0 can be found in the Gradle plugin repo.

```
> Could not resolve all files for configuration ':classpath'.	
   > Could not find com.diffplug.spotless:spotless-lib:2.30.0.	
     Searched in the following locations:	
       - https://plugins.gradle.org/m2/com/diffplug/spotless/spotless-lib/2.30.0/spotless-lib-2.30.0.pom	
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.	
     Required by:	
         project : > com.diffplug.spotless:com.diffplug.spotless.gradle.plugin:6.11.0 > com.diffplug.spotless:spotless-plugin-gradle:6.11.0	
   > Could not find com.diffplug.spotless:spotless-lib-extra:2.30.0.	
     Searched in the following locations:	
       - https://plugins.gradle.org/m2/com/diffplug/spotless/spotless-lib-extra/2.30.0/spotless-lib-extra-2.30.0.pom	
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.	
     Required by:	
         project : > com.diffplug.spotless:com.diffplug.spotless.gradle.plugin:6.11.0 > com.diffplug.spotless:spotless-plugin-gradle:6.11.0
```

**Comment by jvanderwee** [comment] 2022-09-14 14:43
Looks like the CircleCI job which deploys the artifacts is still running https://github.com/diffplug/spotless/runs/8343619081

**Comment by nedtwigg** [comment] 2022-09-14 17:21
Dupe of #1319.

**Closed by nedtwigg** 2022-09-14 17:21 UTC
