### ISSUE TITLE
Respect existing copyright assignment in `LicenseHeaderStep`

### ISSUE THREAD

**Issue by basil** [diffplug/spotless#1677] opened 2023-04-11 21:49 UTC
The [MIT license template](https://choosealicense.com/licenses/mit/) contains a copyright assignment line:

> Copyright (c) [year] [fullname]

`jenkinsci/jenkins` is an 18-year-old MIT licensed project, and our files do not all have the same copyright assignment. For example, one file might have

> Copyright (c) 2004-2009, Sun Microsystems, Inc., Kohsuke Kawaguchi

and another file might have

> Copyright (c) 2015, CloudBees, Inc.

With a template like

> Copyright (c) $YEAR [fullname]

Spotless currently changes the above to

> Copyright (c) 2004-2009 [fullname]

and

> Copyright (c) 2015 [fullname]

We would like it to respect the existing copyright assignment. Reassigning copyright for all files to the same owner is not an option for a project of our age with a complicated lineage dating back to Sun Microsystems, a corporate entity which no longer exists in its original form.

**Comment by nedtwigg** [comment] 2023-04-14 19:06
- dupe of #323.

**Closed by nedtwigg** 2023-04-14 19:06 UTC
