### ISSUE TITLE
A problem was found with the configuration of task ':spotlessJavaCheck'.    /build/spotless/spotlessJava' specified for property 'spotlessOutDirectory' does not exist.

### ISSUE THREAD

**Issue by compilead** [diffplug/spotless#814] opened 2021-03-08 12:30 UTC
If you are submitting a **bug**, please include the following:

- [x] summary of problem
Task :spotlessJavaCheck FAILED
What went wrong:
A problem was found with the configuration of task ':spotlessJavaCheck'.
Directory '......./build/spotless/spotlessJava' specified for property 'spotlessOutDirectory' does not exist.
- [x] gradle or maven version
gradle-5.6
- [x] spotless version
spotless_version = '5.8.2'
- [ ] operating system and version
- [x] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
spotless {
    format 'misc', {
        target '**/*.gradle', '**/*.md', '**/.gitignore'
        trimTrailingWhitespace()
        indentWithSpaces()
        endWithNewline()
    }
    java {
        target project.fileTree(project.rootDir) {
            include '**/*.java'
            exclude 'build/generated/**/*.*'
        }
        googleJavaFormat().aosp()
    }
}
- [ ] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`

If you're just submitting a feature request or question, no need for the above.

**Comment by compilead** [comment] 2021-03-08 12:32
Because of this Pipeline stage is failing for code format check... can anyone help me resolving this issue.

**Comment by nedtwigg** [comment] 2021-03-08 17:28
Dupe of #741, fixed in `5.9.0` (you are using `5.8.2`)

**Comment by compilead** [comment] 2021-03-10 10:21
Hi @nedtwigg,

Even after updating spotless version to 5.9.0 we are getting following issue:
> Task :spotlessJava
Exception caught during execution of command '[/app/vbuild/RHEL7-x86_64/git/2.22.0/bin/git, config, --system, --edit]' in
'/app/vbuild/RHEL7-x86_64/git/2.22.0/bin', return code '128', error message 
'fatal: Invalid path '/<*>/<*>/app/vbuild/RHEL7-x86_64/git/2.22.0/etc': No such file or directory

There is no directory etc. I am confused is it related to soptless or what ?

**Comment by nedtwigg** [comment] 2021-03-10 22:32
That's a *very* strange error trace. Maybe try `--stacktrace`?

**Comment by nedtwigg** [comment] 2021-03-11 19:13
Huzzah, it's fixed! ;-) If you would like further help, it's easier to read your debuginfo if you [read this](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks). As of now, it looks to me like `5.9.0` did in fact fix the issue. If that isn't true, please provide well-formatted, readable details.

**Closed by nedtwigg** 2021-03-11 19:13 UTC
Labels: question
