### ISSUE TITLE
Support for Detekt

### ISSUE THREAD

**Issue by rougsig** [diffplug/spotless#1086] opened 2022-01-12 01:43 UTC
Spotless can work with [diktat](https://github.com/analysis-dev/diktat), but not with [detekt](https://github.com/detekt/detekt).
Diktat is analysis tool too. like detekt .

The main functionality that I want to get from usage spotless with detekt is git ratchet. Detekt haven't that feature. I need to write wrapper to implement it.  It can be cool, if i can use detekt from spotless with git ratchet feature. 

Also i can write PR with detekt support.

Forward from https://github.com/diffplug/spotless/issues/143

**Comment by nedtwigg** [comment] 2022-01-12 19:41
Dupe of #143, I'll reopen that issue. PR welcome :)

**Closed by nedtwigg** 2022-01-12 19:41 UTC
