### ISSUE TITLE
Support for Eclipse formatter 4.22

### ISSUE THREAD

**Issue by Hubry** [diffplug/spotless#1059] opened 2022-01-02 13:02 UTC
4.22 hit last month and it includes a fix for a bug I have hit, [574437 - incorrect formatting in pattern instanceof](https://bugs.eclipse.org/bugs/show_bug.cgi?id=574437).

**Comment by fvgh** [comment] 2022-01-02 13:31
The process is already ongoing.
Currently waiting for #1054 and #1058.

**Comment by Hubry** [comment] 2022-01-02 13:39
Oh, I have searched through the issue tab and PRs a few times, but I guess I didn't read into descriptions fully.

Feel free to close this if that would be preferred.

**Comment by nedtwigg** [comment] 2022-01-06 07:02
It's nice to have this tracking issue for `4.22`. I expect it'll be a few weeks before this gets in due to delays caused by me and the build system :(

**Comment by Frettman** [comment] 2023-01-01 16:20
Any news on this?

**Comment by nedtwigg** [comment] 2023-01-11 22:28
I expect to have some progress to show on this next week. Our `_ext` project has worked great to get us this far, but required a lot of maintenance. I think we can do something easier than that now.

**Comment by nedtwigg** [comment] 2023-01-25 13:50
This is coming soon via

- #1524

**Comment by JamesChenX** [comment] 2023-01-27 08:42
@nedtwigg Hi, is there a plan for when the PR https://github.com/diffplug/spotless/pull/1524 will be merged and released (e.g. A week or month)? We are waiting for the new the Eclipse formatter to format our large codebase.
Thanks for the wonderful project.

**Comment by nedtwigg** [comment] 2023-01-27 17:45
I'm confident it will be less than 2 weeks.

**Comment by torito** [comment] 2023-03-31 11:41
any update on this issue ?

**Comment by nedtwigg** [comment] 2023-03-31 14:54
Thanks @torito, I forgot to update this issue.

- published in `plugin-gradle 6.17.0`
- published in `plugin-maven 2.35.0`

**Closed by nedtwigg** 2023-03-31 14:54 UTC
Labels: enhancement
