### ISSUE TITLE
Ktlint rule for disabling Import ordering is not honored

### ISSUE THREAD

**Issue by sp00ne** [diffplug/spotless#582] opened 2020-05-27 13:16 UTC
## Issue 
The issue at hand is that java imports are placed erroneously when autoformatting in the IDE. As a result, ktlint has exposed a linting option of disabling the import-order rule through `.editorconfig`: 

```
disabled_rules = import-ordering
```
For reference see: https://github.com/pinterest/ktlint/issues/527
Spotless however, does not honor this and throws exception when running the check. 

## .editorConfig
```
# https://github.com/shyiko/ktlint#editorconfig

root = true

[*.{kt,kts,xml}]
indent_style = space
indent_size = 4
charset = utf-8
end_of_line = lf
trim_trailing_whitespace = true
insert_final_newline = true

[*.{kt,kts}]
max_line_length = 165
disabled_rules = import-ordering # Added because IDEA does not respect alphabetical ordering (https://github.com/JetBrains/kotlin/pull/3336)
```

## Stack trace from `spotlessCheck`
```
> The following files had format violations:
      app/src/main/java/com/sl/slbiljetter/util/extensions/LiveDataExtensions.kt
          @@ -7,16 +7,16 @@
           import·androidx.lifecycle.Observer
           import·androidx.lifecycle.asFlow
           import·androidx.lifecycle.asLiveData
          +import·java.util.concurrent.CountDownLatch
          +import·java.util.concurrent.TimeUnit
          +import·java.util.concurrent.TimeoutException
          +import·kotlin.math.roundToLong
           import·kotlinx.coroutines.CoroutineDispatcher
           import·kotlinx.coroutines.Dispatchers
           import·kotlinx.coroutines.delay
           import·kotlinx.coroutines.flow.debounce
           import·kotlinx.coroutines.flow.flatMapConcat
           import·kotlinx.coroutines.flow.flow
          -import·java.util.concurrent.CountDownLatch
          -import·java.util.concurrent.TimeUnit
          -import·java.util.concurrent.TimeoutException
          -import·kotlin.math.roundToLong
           

```

**Comment by nedtwigg** [comment] 2020-05-27 18:09
Duplicate of #142

**Closed by nedtwigg** 2020-05-27 18:09 UTC
