### ISSUE TITLE
Allow ktlint to scan the whole project

### ISSUE THREAD

**Issue by flopes89** [diffplug/spotless#2036] opened 2024-02-06 13:59 UTC
When using ktlint, the execution stops when finding the first violation.

I would like to allow ktlint to scan the whole project and collect violations as a whole, instead of going through them one by one and executing it again and again.

**Comment by nedtwigg** [comment] 2024-02-12 23:42
- Dupe of #287

**Closed by nedtwigg** 2024-02-12 23:42 UTC
Labels: enhancement
