### ISSUE TITLE
EclipseWTP JSON Formatting Issue with Arrays

### ISSUE THREAD

**Issue by Tolgeros** [diffplug/spotless#344] opened 2019-01-28 16:35 UTC
I have a Java app built with Maven that contains JSON files that I would like to format.  I see the README specifying EclipseWTP formatting options, which I'm trying out from the latest snapshot (1.18-SNAPSHOT) in oss-sonatype.

Here are the changes made to my pom.xml:

```
		<repository>
		    <id>oss-sonatype</id>
		    <name>oss-sonatype</name>
		    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
		    <snapshots>
		        <enabled>true</enabled>
		    </snapshots>
		</repository>
```
...
```
		<dependency>
		  <groupId>com.diffplug.spotless</groupId>
		  <artifactId>spotless-maven-plugin</artifactId>
		  <version>1.18.0-SNAPSHOT</version>
		</dependency>
```
...
```
            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <version>1.18.0-SNAPSHOT</version>
                <configuration>
                	<formats>
                		<format>
		                    <includes>
		                        <include>src/**/resources/**/*.json</include>
		                    </includes>
		                    <eclipseWtp>
                                        <type>JSON</type>
                                        <files>
                                            <file>${basedir}/target/org.eclipse.wst.json.core.prefs</file>
                                        </files>
		                    </eclipseWtp>
                		</format>
                	</formats>
                </configuration>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

I can see that it is now formatting all my "normal" JSON files properly (ones with curly braces at the top level), except there is problem with array JSON files.  If a JSON file contains an array (square brackets) at the top level, it puts an extra ] at the end.

i.e. Before spotless:apply:
```
[
  {
    "paths": [],
    "payloads": [
      {
        "foo": "bar"
      }
    ]
  }
]
```

After:
```
[
  {
    "paths": [],
    "payloads": [
      {
        "foo": "bar"
      }
    ]
  }
]
]
```

I've searched for this issue from an Eclipse WTP perspective and cannot find any other examples of this happening.  I've tried playing around with the prefs as well as removing the "files" tag entirely to use default and the result is always the same.  Since this is a brand new feature for spotless, I'm hoping this can be looked at.

**Comment by fvgh** [comment] 2019-01-28 19:58
Thanks for your error description. 

I was able to reproduce the problem with the Maven and Gradle plugin using Eclipse default configuration (omitting the configuration). For Gradle plugin I needed to add paddedCell otherwise I got an exception.
FYI: I provided the test files in [GIST](https://gist.github.com/fvgh/8d9232e446dd5f2d7346de0d637df754).

Neither the Oxygen Eclipse (that's the version the Spotless WTP feature is currently using), nor the Photon Eclipse shows the problem, so it is some problem on my/our side.

**Comment by fvgh** [comment] 2019-01-28 20:17
Unfortunately I cannot reproduce the problem in the Spotless WTP feature (see [test extension](https://github.com/diffplug/spotless/compare/issue_344)).
I am afraid I am a little bit at a loss where the problem comes from. I am quite busy at the moment, so it may take more than a week. :disappointed:

**Comment by Tolgeros** [comment] 2019-02-09 19:37
Thanks for acknowledging the issue and testing it out.  I did notice in that test extension your UNFORMATTED_ARRAY and FORMATTED_ARRAY do not have a closing ] at the end.

**Comment by fvgh** [comment] 2019-02-10 18:33
@Tolgeros Thanks. Found and solved the problem. Will close this issue as soon as new version of Spotless extension is published and integrated into the Gradle&Maven plugin.

**Closed** 2019-02-11 20:47 UTC
Labels: bug
