### ISSUE TITLE
Eclipse formatter fails to respect comment.line_length

### ISSUE THREAD

**Issue by DominicAnelloSonos** [diffplug/spotless#788] opened 2021-02-03 17:07 UTC
I've encountered an issue where the spotless Maven plugin appears to be spuriously flagging a violation in a Javadoc comment by suggesting to lengthen a line beyond the configured comment line length.

The Eclipse format.xml used in the configuration has the following setting:
```
<setting id="org.eclipse.jdt.core.formatter.comment.line_length" value="120"/>
```
The comment line in question is 117 characters long.  Spotless fails on the line suggesting an edit to wrap the line one word later.  However this would bring the line length up to 123, violating the formatting rule.  When I run the same formatter in the Eclipse IDE, there is no such problem, and indeed it will undo the edit made by `spotless:apply`.

Here is the suggested edit:
```
-·····*·@return·an·Optional·value,·which·may·be·empty,·that·contains·the·first·cause·that·contains·{@code·key}·and·the
-·····*·········value·associated·matches·{@code·p}.
+·····*·@return·an·Optional·value,·which·may·be·empty,·that·contains·the·first·cause·that·contains·{@code·key}·and·the·value
+·····*·········associated·matches·{@code·p}.
```

**Versions:**
* Spotless: `2.7.0`
* Spotless Eclipse Formatter: `4.18.0`
* Maven: `2.6.3`
* Eclipse IDE: `2020-12 (4.18.0)`
* OS: Mac OS `10.15.7`

Here is the Eclipse formatter configuration I am using: [JavaFormat.txt](https://github.com/diffplug/spotless/files/5920150/JavaFormat.txt)

**Spotless Plugin Config**
```
<plugin>                                                                                            
    <groupId>com.diffplug.spotless</groupId>                                                        
    <artifactId>spotless-maven-plugin</artifactId>                                                  
    <version>${spotless.version}</version>                                                          
                                                                                                    
    <configuration>                                                                                 
        <ratchetFrom>origin/main</ratchetFrom>                                                      
        <encoding>UTF-8</encoding>                                                                  
        <endWithNewline />                                                                          
                                                                                                    
        <java>                                                                                      
            <toggleOffOn>                                                                           
                <off>@formatter:off</off>                                                           
                <on>@formatter:on</on>                                                              
            </toggleOffOn>                                                                          
            <removeUnusedImports />                                                                 
            <eclipse>                                                                               
                <version>4.18.0</version>                                                           
                <file>${project.basedir}/support/format/JavaFormat.xml</file>                    
            </eclipse>                                                                              
            <importOrder>                                                                           
                <file>${project.basedir}/support/format/JavaEclipse.importorder</file>      
            </importOrder>                                                                          
            <licenseHeader>                                                                         
                <file>${project.basedir}/support/format/copyright-header-java.txt</file>         
                <delimiter>package</delimiter>                                                      
            </licenseHeader>                                                                        
        </java>                                                                                     
    </configuration>                                                                                
                                                                                                    
    <executions>                                                                                    
        <execution>                                                                                 
            <goals>                                                                                 
                <goal>check</goal>                                                                  
            </goals>                                                                                
        </execution>                                                                                
    </executions>                                                                                   
</plugin>                                                                                           
```

**Stacktrace**
```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.7.0:check (default) on project lib-okta-model: The following files had format violations:
    src/main/java/com/mycompany/services/okta/model/OktaError.java
        @@ -77,8 +77,8 @@
         ·····*·@param·key·the·key·to·consider·in·each·cause.·This·value·should·be·a·constant·drawn·from·{@link·CauseFields}.
         ·····*·@param·p·the·pattern·to·match·against·the·value·mapped·to·{@code·key}.
         ·····*
        -·····*·@return·an·Optional·value,·which·may·be·empty,·that·contains·the·first·cause·that·contains·{@code·key}·and·the
        -·····*·········value·associated·matches·{@code·p}.
        +·····*·@return·an·Optional·value,·which·may·be·empty,·that·contains·the·first·cause·that·contains·{@code·key}·and·the·value
        +·····*·········associated·matches·{@code·p}.
         ·····*
         ·····*·@since·1.3.3
         ·····*/
Run 'mvn spotless:apply' to fix these violations.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: The following files had format violations:
    src/main/java/com/mycompany/services/okta/model/OktaError.java
        @@ -77,8 +77,8 @@
         ·····*·@param·key·the·key·to·consider·in·each·cause.·This·value·should·be·a·constant·drawn·from·{@link·CauseFields}.
         ·····*·@param·p·the·pattern·to·match·against·the·value·mapped·to·{@code·key}.
         ·····*
        -·····*·@return·an·Optional·value,·which·may·be·empty,·that·contains·the·first·cause·that·contains·{@code·key}·and·the
        -·····*·········value·associated·matches·{@code·p}.
        +·····*·@return·an·Optional·value,·which·may·be·empty,·that·contains·the·first·cause·that·contains·{@code·key}·and·the·value
        +·····*·········associated·matches·{@code·p}.
         ·····*
         ·····*·@since·1.3.3
         ·····*/
Run 'mvn spotless:apply' to fix these violations.
    at com.diffplug.spotless.maven.SpotlessCheckMojo.process (SpotlessCheckMojo.java:66)
    at com.diffplug.spotless.maven.AbstractSpotlessMojo.execute (AbstractSpotlessMojo.java:146)
    at com.diffplug.spotless.maven.AbstractSpotlessMojo.execute (AbstractSpotlessMojo.java:137)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

**Comment by fvgh** [comment] 2021-02-07 13:27
@DominicAnelloSonos I am afraid I cannot reproduce your problem.
Input:
```java
class Test {

    /**
     * @return an Optional value, which may be empty, that contains the first cause that contains {@code key} and the value associated matches {@code p}
     */
    public static int test() {
        return 0;
    }
}
```
POM:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>my</groupId>
  <artifactId>test</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>MvnTest</name>
  <description>Check maven</description>
  <packaging>jar</packaging>
  <properties>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>
  <build>
    <plugins>
      <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
        <version>2.7.0</version>
        <configuration>
          <java>
            <eclipse>
              <version>4.18.0</version>
              <file>${project.basedir}/JavaFormat.xml</file>
            </eclipse>
          </java>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```
Output after `mvn spotless:apply`
```java
class Test {

    /**
     * @return an Optional value, which may be empty, that contains the first cause that contains {@code key} and the
     *         value associated matches {@code p}
     */
    public static int test() {
        return 0;
    }
}
```

Could you please check where it comes in and provide a small example (maybe on GIST)? Or have I misinterpret something?

**Comment by DominicAnelloSonos** [comment] 2021-02-09 16:30
@fvgh. thanks for looking into it.  I'll see if I can reproduce on a smaller project and get back to you.

**Comment by fvgh** [comment] 2021-04-04 08:58
Closing issue. @DominicAnelloSonos, please reopen if you have something for further investigation.

**Closed by fvgh** 2021-04-04 08:58 UTC
Labels: bug-unconfirmed
