### ISSUE TITLE
spotlessInternalRegisterDependencies taking 18s to run

### ISSUE THREAD

**Issue by xenoterracide** [diffplug/spotless#894] opened 2021-07-13 17:06 UTC
is there anything I can do to change this, this is incredibly slow for a git commit pre-commit hook. I"m not certain what it could be doing every time that it's so slow.

```
> Task :spotlessInternalRegisterDependencies UP-TO-DATE
Caching disabled for task ':spotlessInternalRegisterDependencies' because:
  Caching has not been enabled for the task
Skipping task ':spotlessInternalRegisterDependencies' as it is up-to-date.
:spotlessInternalRegisterDependencies (Thread[Execution worker for ':',5,main]) completed. Took 18.731 secs.
:app:spotlessJava (Thread[Execution worker for ':',5,main]) started.
```

```kt
spotless {
  val isCI = providers.environmentVariable("CI").forUseAtConfigurationTime().isPresent
  ratchetFrom = if (isCI) "HEAD~1" else "HEAD"
  java {
    removeUnusedImports()
    // importOrder()
    licenseHeader(
      String.format(
        "/*%n" +
          " * $copyright%n" +
          " * $license%n" +
          " * $licenseSimple%n" +
          " */%n"
      )
    )
    prettier(mapOf("prettier-plugin-java" to "1.x"))
  }
  kotlinGradle {
    ktfmt().googleStyle()
  }
  format("xml") {
    target("*.xml")
    prettier().config(mapOf("@prettier/plugin-xml" to "0.x"))
  }
  format("properties") {
    target("*.properties")
    prettier().config(mapOf("prettier-plugin-properties" to "0.x"))
  }
}
```

```
 ./gradlew -p buildSrc dependencyInsight --configuration runtimeClasspath --dependency spotless                                                  # backend -> master +
Type-safe dependency accessors is an incubating feature.

> Task :dependencyInsight
com.diffplug.spotless:spotless-lib:2.15.1
   variant "runtimeElements" [
      org.gradle.category                = library
      org.gradle.dependency.bundling     = external
      org.gradle.jvm.version             = 8 (compatible with: 11)
      org.gradle.libraryelements         = jar
      org.gradle.usage                   = java-runtime
      org.gradle.status                  = release (not requested)

      Requested attributes not found in the selected variant:
         org.gradle.jvm.environment         = standard-jvm
         org.jetbrains.kotlin.platform.type = jvm
   ]
   Selection reasons:
      - By constraint : dependency was locked to version '2.15.1'
      - By ancestor

com.diffplug.spotless:spotless-lib:{strictly 2.15.1} -> 2.15.1
\--- runtimeClasspath

com.diffplug.spotless:spotless-lib:2.15.1
+--- com.diffplug.spotless:spotless-lib-extra:2.15.1
|    +--- runtimeClasspath (requested com.diffplug.spotless:spotless-lib-extra:{strictly 2.15.1})
|    \--- com.diffplug.spotless:spotless-plugin-gradle:5.14.1
|         \--- runtimeClasspath (requested com.diffplug.spotless:spotless-plugin-gradle:5.+)
\--- com.diffplug.spotless:spotless-plugin-gradle:5.14.1 (*)

com.diffplug.spotless:spotless-lib-extra:2.15.1
   variant "runtimeElements" [
      org.gradle.category                = library
      org.gradle.dependency.bundling     = external
      org.gradle.jvm.version             = 8 (compatible with: 11)
      org.gradle.libraryelements         = jar
      org.gradle.usage                   = java-runtime
      org.gradle.status                  = release (not requested)

      Requested attributes not found in the selected variant:
         org.gradle.jvm.environment         = standard-jvm
         org.jetbrains.kotlin.platform.type = jvm
   ]
   Selection reasons:
      - By constraint : dependency was locked to version '2.15.1'
      - By ancestor

com.diffplug.spotless:spotless-lib-extra:{strictly 2.15.1} -> 2.15.1
\--- runtimeClasspath

com.diffplug.spotless:spotless-lib-extra:2.15.1
\--- com.diffplug.spotless:spotless-plugin-gradle:5.14.1
     \--- runtimeClasspath (requested com.diffplug.spotless:spotless-plugin-gradle:5.+)

com.diffplug.spotless:spotless-plugin-gradle:5.14.1
   variant "runtime" [
      org.gradle.status                  = release (not requested)
      org.gradle.usage                   = java-runtime
      org.gradle.libraryelements         = jar
      org.gradle.category                = library

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling     = external
         org.gradle.jvm.environment         = standard-jvm
         org.jetbrains.kotlin.platform.type = jvm
         org.gradle.jvm.version             = 11
   ]
   Selection reasons:
      - By constraint : dependency was locked to version '5.14.1'

com.diffplug.spotless:spotless-plugin-gradle:{strictly 5.14.1} -> 5.14.1
\--- runtimeClasspath

com.diffplug.spotless:spotless-plugin-gradle:5.+ -> 5.14.1
\--- runtimeClasspath

(*) - dependencies omitted (listed previously)

A web-based, searchable dependency report is available by adding the --scan option.

BUILD SUCCESSFUL in 7s
1 actionable task: 1 executed
```

```./gradlew --version                                                                                                                             # backend -> master +

------------------------------------------------------------
Gradle 7.1.1
------------------------------------------------------------

Build time:   2021-07-02 12:16:43 UTC
Revision:     774525a055494e0ece39f522ac7ad17498ce032c

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.11 (AdoptOpenJDK 11.0.11+9)
OS:           Linux 5.10.42-1-MANJARO amd64
```

**Comment by nedtwigg** [comment] 2021-07-13 18:16
This is all due to the prettier(), dupe of https://github.com/diffplug/spotless/issues/766

**Closed** 2021-07-13 18:16 UTC
