### ISSUE TITLE
Gradle ktlint check should display the violated rule name

### ISSUE THREAD

**Issue by gotson** [diffplug/spotless#1551] opened 2023-02-02 06:52 UTC
- [x] gradle version: 7.6
- [x] spotless version: 6.14.0
- [x] operating system and version: macOS 13.2
- [x] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible

When running `spotlessCheck`, the violated rules are not mentioned.

Here is the output of `spotlessCheck`:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':komga:spotlessKotlinCheck'.
> The following files had format violations:
      src/main/kotlin/org/gotson/komga/application/tasks/TaskEmitter.kt
          @@ -63,10 +63,11 @@
           ··}
           
           ··fun·hashBooksWithoutHash(library:·Library)·{
          -····if·(library.hashFiles)
          +····if·(library.hashFiles)·{
           ······bookRepository.findAllByLibraryIdAndWithEmptyHash(library.id).forEach·{
           ········submitTask(Task.HashBook(it.id,·LOWEST_PRIORITY,·it.seriesId))
           ······}
          +····}
           ··}
           
           ··fun·findBooksWithMissingPageHash(library:·Library,·priority:·Int·=·DEFAULT_PRIORITY)·{
          @@ -86,10 +87,11 @@
           ··}
           
           ··fun·repairExtensions(library:·Library,·priority:·Int·=·DEFAULT_PRIORITY)·{
          -····if·(library.repairExtensions)
          +····if·(library.repairExtensions)·{
           ······bookConverter.getMismatchedExtensionBooks(library).forEach·{
           ········submitTask(Task.RepairExtension(it.id,·priority,·it.seriesId))
           ······}
          +····}
           ··}
           
           ··fun·findDuplicatePagesToDelete(library:·Library,·priority:·Int·=·DEFAULT_PRIORITY)·{
  Run './gradlew :komga:spotlessApply' to fix these violations.
```

In comparison, here is the output of the `ktlint` command line:

```
/Users/groebroeck/Dev/komga/komga/src/main/kotlin/org/gotson/komga/application/tasks/TaskEmitter.kt:67:7: Missing { ... } (multiline-if-else)
/Users/groebroeck/Dev/komga/komga/src/main/kotlin/org/gotson/komga/application/tasks/TaskEmitter.kt:90:7: Missing { ... } (multiline-if-else)
```

Notice how the rule `multiline-if-else` is mentioned in there.

In addition, when running in IntelliJ, the filenames in the output of spotless are not links, and thus not clickable. It would be great to be able to click on the file names so i can open them directly.
<img width="744" alt="image" src="https://user-images.githubusercontent.com/2139133/216252731-77caa2c6-5a10-4f8a-a6a0-eb7e2e8d2c0c.png">

In comparison, the command line output of `ktlint` is clickable.
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/2139133/216252766-10c65658-a412-4970-afc8-e670d58bdd74.png">

Configuration:

```kotlin
configure<com.diffplug.gradle.spotless.SpotlessExtension> {
    kotlin {
      targetExclude("**/db/migration/**")
      ktlint("0.48.2")
    }
  }
```

**Comment by nedtwigg** [comment] 2023-02-02 19:21
- dupe of #1278

**Closed by nedtwigg** 2023-02-02 19:21 UTC
