### ISSUE TITLE
Spotless 6.0 failures with message to add repositories block, but said block exists

### ISSUE THREAD

**Issue by ZacSweers** [diffplug/spotless#1002] opened 2021-11-28 03:15 UTC
While trying to make a public repro for https://github.com/gradle/gradle/issues/19113 I encountered a different issue where using spotless in a `plugins {}` block seems to miss any repositories declared.

- Gradle 7.3
- Spotless version 6.0.0
- OS - repros on macOS and linux

Repro PR: https://github.com/slackhq/slack-lints/pull/10

Result: 

```
> Task :spotlessKotlin FAILED
You need to add a repository containing the '[com.pinterest:ktlint:0.41.0]' artifact in 'build.gradle'.
E.g.: 'repositories { mavenCentral() }'
```

Even though it is present in the build file

```kotlin
plugins {
  id("com.diffplug.spotless") version "6.0.0" apply false
}

// ...

allprojects {
  repositories {
    google()
    mavenCentral() // KtLint is available here!
  }

  apply(plugin = "com.diffplug.spotless")
  configure<SpotlessExtension> {
    // ...
    val ktlintVersion = "0.41.0"
    val ktlintUserData = mapOf("indent_size" to "2", "continuation_indent_size" to "2")
    kotlin {
      target("**/*.kt")
      ktlint(ktlintVersion).userData(ktlintUserData)
      trimTrailingWhitespace()
      endWithNewline()
      licenseHeaderFile(rootProject.file("spotless/spotless.kt"))
      targetExclude("**/spotless.kt")
    }
    kotlinGradle {
      ktlint(ktlintVersion).userData(ktlintUserData)
      trimTrailingWhitespace()
      endWithNewline()
      licenseHeaderFile(
        rootProject.file("spotless/spotless.kt"),
        "(import|plugins|buildscript|dependencies|pluginManagement)"
      )
    }
  }
}
```

**Comment by nedtwigg** [comment] 2021-11-28 16:07
I think this is a dupe of https://github.com/diffplug/spotless/issues/993

**Comment by ZacSweers** [comment] 2021-11-28 16:26
Ah yep seems so. hope the repro is helpful!

**Closed** 2021-11-28 16:26 UTC
