### ISSUE TITLE
(Gradle) wrong intendentions wigh googleJavaFormat 1.9

### ISSUE THREAD

**Issue by Ksenia989** [diffplug/spotless#714] opened 2020-10-13 14:59 UTC
Hi! I'm using your plugin to reformat code before compilation. The issue is that in some cases it does not format indentations properly (see picture below)
Gradle: 5.4.1
Spotless version 5.6.1
Operating system - Windows 10

Full Spotless configuration block(s):
```
plugins {
	id "com.diffplug.spotless" version "5.6.1"
}
```

```
spotless {
	java {
		googleJavaFormat("1.9")
		removeUnusedImports()
		importOrder('java', 'javax', '')
		indentWithTabs(2)
		indentWithSpaces(4)
		endWithNewline()
	}
}
```

```
compileJava {
	dependsOn spotlessJavaApply
}
```

Error 1: should be 8 spaces, but we're seeing 16 instead (sorry, can't show you the real code)
![image](https://user-images.githubusercontent.com/25930885/95876566-de7ffb80-0d7b-11eb-8c21-bb678a524488.png)

Error 2: unnecessary line breaking after annotation param, even if it doesn't require a lot of space to put at least one parameter on the first line.
![image](https://user-images.githubusercontent.com/25930885/95877431-c65cac00-0d7c-11eb-8b98-802dd3f3161f.png)

No errors in  `gradlew spotless[Apply/Check] --stacktrace`

**Comment by jbduncan** [comment] 2020-10-13 17:41
I believe that everything you're seeing are intended side-effects of [google-java-format](https://github.com/google/google-java-format). It looks like you're replacing every 2 spaces with tabs, is that right? If so, I don't believe there's an easy way to fix this...

You could report it to [the google-java-format team](https://github.com/google/google-java-format/issues), but I'd be surprised if they agreed to change the indentation, because they like to follow the [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html) and something called [The Rectangle Rule](https://github.com/google/google-java-format/wiki/The-Rectangle-Rule), and I don't yet have any reason to believe that what you're seeing violates either of those.

If you need more flexibility, try [Eclipse JDT](https://github.com/diffplug/spotless/tree/main/plugin-gradle#eclipse-jdt). But if that doesn't do what you want, you may have better luck with [Prettier](https://github.com/diffplug/spotless/tree/main/plugin-gradle#prettier) (but note that it requires Node.js to be installed on your computer to work).

Let us know if you need any further help with this. :)

**Comment by jbduncan** [comment] 2020-10-13 17:45
Here's another option: we recently introduced [`spotless:(off|on)`](https://github.com/diffplug/spotless/tree/main/plugin-gradle#spotlessoff-and-spotlesson) tags, which you can use to highlight bits of code that Spotless shouldn't touch. You can then manually format those bits of code to your liking.

**Comment by Ksenia989** [comment] 2020-10-14 06:05
Thanks a lot! I'll try the Eclipse JDT. Prettier plugin for java is for maven, I'm using gradle anyway. 

You asked about spaces and tabs: it works proportionally the same (just 8 instead of 4) spaces without my indentWithTabs(2) and 
 indentWithSpaces(4) setting:
![image](https://user-images.githubusercontent.com/25930885/95949623-b637e180-0dfb-11eb-874e-ec7efc0b9868.png)

**Comment by jbduncan** [comment] 2020-10-14 08:49
> Prettier plugin for java is for maven, I'm using gradle anyway.

Oh, really? I thought I linked you to our docs for using Prettier through our Gradle plugin, but if I linked the Maven plugin docs instead, then I'm very sorry! Is this link any better? https://github.com/diffplug/spotless/tree/main/plugin-gradle#prettier

And thanks for the screenshot, it clarifies things for me. I can confirm that that's definitely the expected behaviour of google-java-format.

I'm going to close this issue then under the assumption that everything's fine, but feel free to reopen if you need any further help.

**Closed by jbduncan** 2020-10-14 08:49 UTC
Labels: question
