### ISSUE TITLE
java.lang.NoClassDefFoundError with Java 9

### ISSUE THREAD

**Issue by boris-petrov** [diffplug/spotless#147] opened 2017-09-25 09:10 UTC
When using JDK 9, the following happens:

```
Step 'removeUnusedImports' found problem in 'some-source.java':
javax/tools/JavaFileManager$Location
java.lang.NoClassDefFoundError: javax/tools/JavaFileManager$Location
        at com.diffplug.spotless.java.GoogleJavaFormatStep$State.createRemoveUnusedImportsOnly(GoogleJavaFormatStep.java:113)
        at com.diffplug.spotless.FormatterStepImpl$Standard.format(FormatterStepImpl.java:76)
        at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:76)
        at com.diffplug.spotless.Formatter.compute(Formatter.java:230)
        at com.diffplug.spotless.Formatter.isClean(Formatter.java:167)
        at com.diffplug.gradle.spotless.SpotlessTask.check(SpotlessTask.java:216)
        at com.diffplug.gradle.spotless.SpotlessTask.performAction(SpotlessTask.java:172)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:179)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:135)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:122)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        ...
```

**Comment by jbduncan** [comment] 2017-09-25 09:42
Hi @boris-petrov, thanks for the bug report! It looks to me that you're calling either `removeUnusedImports()` or `googleJavaFormat()` in your Gradle buildscript? Could you provide us with a reproducible [MVCE](https://stackoverflow.com/help/mcve) that would allow us to investigate this further?

**Comment by boris-petrov** [comment] 2017-09-25 10:36
Hi @jbduncan - yes, I'm calling `removeUnusedImports()`. Well, a really simple reproduction is:

```gradle
plugins {
	id 'com.diffplug.gradle.spotless' version '3.5.2'
}

repositories {
	mavenCentral()
	jcenter()
}

spotless {
	java {
		target fileTree('src') {
			include '**/*.java'
		}

		removeUnusedImports()
	}
}
```

And add a single file to `src/main/java` and run `gradle spotlessJavaCheck`. Be sure to use JDK 9.

**Comment by jbduncan** [comment] 2017-09-25 11:17
Many thanks @boris-petrov! It actually occurs to me now that this issue is likely a dupe of https://github.com/diffplug/spotless/issues/83, so I'll close it for now, as resolving one should resolve the other. If you think, however, that this _isn't_ a dupe, please let me know why and I'll reopen. :)

**Closed by jbduncan** 2017-09-25 11:17 UTC

**Comment by jbduncan** [comment] 2017-09-25 11:19
Apologies for not noticing earlier about this issue being a dupe!

**Comment by boris-petrov** [comment] 2017-09-25 11:19
Not a problem! Apologies from my side that I didn't see an open issue for that! Thanks!
